import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import { describe } from './describe/index.js';
import { type Description } from './describe/types.js';
import { type CodecSpec, normalizeNativeEvent } from './codec.js';
import { deriveProducerEventId, sealPayload } from './envelope.js';
import { redactSecrets, reducePath, reduceUrl, topLevelKeys } from './redact.js';
import { escapeControlCharacters, safeText, truncate } from './text.js';
import { normalizeToolName } from './tool-normalize.js';

const fixturesDir = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  '__fixtures__',
  'describe'
);

type GoldenCase = {
  name: string;
  tool: string;
  input: unknown;
  projectRoot: string | null;
  expect: Description;
};

const golden = JSON.parse(readFileSync(path.join(fixturesDir, 'golden.json'), 'utf8')) as Record<
  string,
  GoldenCase[]
>;

/**
 * The golden fixtures are the real test of this module.
 *
 * A formatter is a function whose output a human being reads and then approves a shell command
 * on the strength of. "It looked right when I wrote it" is not a property; a recorded exact
 * output that fails loudly when someone changes a regex is.
 */
test('describe: golden fixtures', () => {
  for (const [group, cases] of Object.entries(golden)) {
    for (const entry of cases) {
      const actual = describe({
        tool: entry.tool,
        input: entry.input,
        projectRoot: entry.projectRoot
      });
      assert.deepEqual(actual, entry.expect, `${group}/${entry.name}`);
    }
  }
});

/**
 * The property the golden files exist to protect, asserted directly rather than by inspection.
 *
 * Every fixture carries content a formatter must never emit — file bodies, credential values,
 * query-string tokens. This walks the rendered output of every case looking for them. It is
 * deliberately separate from the golden comparison: a golden file can be regenerated by someone
 * who does not notice that the new output now contains a secret, and this test cannot.
 */
test('describe: no fixture output contains forbidden content', () => {
  const forbidden = [
    'nuclear codes',
    'AKIAIOSFODNN7EXAMPLE',
    'super-secret',
    'hunter2',
    'ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ012345',
    'export const a = 1',
    'long body'
  ];
  for (const cases of Object.values(golden)) {
    for (const entry of cases) {
      const rendered = JSON.stringify(
        describe({ tool: entry.tool, input: entry.input, projectRoot: entry.projectRoot })
      );
      for (const needle of forbidden) {
        assert.ok(!rendered.includes(needle), `${entry.name} leaked ${JSON.stringify(needle)}`);
      }
    }
  }
});

test('describe: a throwing formatter degrades to the generic card, never to raw passthrough', () => {
  // A getter that throws is the closest stand-in for the real failure mode: a formatter
  // reaching into an input shape the harness changed under it.
  const hostile = {
    get command(): string {
      throw new Error('boom');
    },
    marker: 'safe-key'
  };
  const result = describe({ tool: 'shell', input: hostile });
  assert.equal(result.action, 'Use a tool (description unavailable)');
  // Key names still surface — they are structural, and structure is what the generic card
  // is for. The getter that threw is one of them.
  assert.deepEqual(result.keys, ['command', 'marker']);
  assert.equal(result.detail, 'input keys: command, marker');
});

test('text: control characters are escaped and truncation is explicit', () => {
  assert.equal(escapeControlCharacters('a\nb\tc'), 'a\\nb\\tc');
  assert.equal(escapeControlCharacters('a‮b'), 'ab');
  assert.equal(truncate('abcdef', 3).text, 'abc…[+3 chars]');
  assert.equal(truncate('abcdef', 3).truncated, true);
  assert.equal(safeText('  a   b  ').text, 'a b');
  assert.equal(safeText(42).text, '');
});

test('redact: secret families are masked and reported', () => {
  const token = redactSecrets('token is out_abcdefgh123456789');
  assert.equal(token.text, 'token is [redacted]');
  assert.deepEqual(token.redactedPatterns, ['overlord-user-token']);

  // The key half survives: knowing a command sets DATABASE_PASSWORD is useful context, and
  // knowing its value is precisely the thing that must not be stored.
  const assigned = redactSecrets('DATABASE_PASSWORD=hunter2 node app.js');
  assert.equal(assigned.text, 'DATABASE_PASSWORD=[redacted] node app.js');

  assert.deepEqual(redactSecrets('nothing here').redactedPatterns, []);
});

test('redact: paths outside the project keep only a basename', () => {
  assert.deepEqual(reducePath('/repo/src/a.ts', '/repo'), {
    display: 'src/a.ts',
    outsideProject: false,
    nonAscii: false
  });
  // `/Users/jake/clients/acme/…` discloses a client list. The directory structure is itself
  // content once we are outside the project.
  assert.deepEqual(reducePath('/Users/jake/clients/acme/report.pdf', '/repo'), {
    display: 'report.pdf',
    outsideProject: true,
    nonAscii: false
  });
  assert.equal(reducePath('src/a.ts', '/repo')?.outsideProject, false);
  assert.equal(reducePath('', '/repo'), null);
});

test('redact: query strings never survive', () => {
  const reduced = reduceUrl('https://api.example.com/v1?token=leak#frag');
  assert.equal(reduced?.display, 'https://api.example.com/v1');
  assert.equal(reduced?.hadQuery, true);
  assert.equal(reduceUrl('::::')?.display, '[unparseable url]');
});

test('redact: topLevelKeys emits structure only, sorted and bounded', () => {
  const many = Object.fromEntries(Array.from({ length: 30 }, (_, i) => [`k${i}`, 'value']));
  const result = topLevelKeys(many);
  assert.equal(result.keys.length, 20);
  assert.equal(result.truncated, true);
  assert.ok(!result.keys.includes('value'));
  assert.deepEqual(topLevelKeys([1, 2]).keys, []);
});

test('tool-normalize: names map exactly, never by substring', () => {
  assert.equal(normalizeToolName('Bash'), 'shell');
  assert.equal(normalizeToolName('run_terminal_cmd'), 'shell');
  assert.equal(normalizeToolName('MultiEdit'), 'edit');
  assert.equal(normalizeToolName('NotebookRead'), 'read');
  assert.equal(normalizeToolName('mcp__github__create_issue'), 'mcp');
  // Not a substring match: an unknown tool whose name merely contains "read" must not be
  // handed to the read formatter, which would render its input as if it were a path.
  assert.equal(normalizeToolName('ThreadInspector'), 'generic');
  assert.equal(normalizeToolName(undefined), 'generic');
});

test('envelope: producer ids are content-derived, so a replay deduplicates', () => {
  const args = {
    adapterKey: 'claude',
    nativeSessionId: 'sess-1',
    nativeEvent: 'PostToolUse',
    parts: ['shell', 'yarn test']
  };
  assert.equal(deriveProducerEventId(args), deriveProducerEventId(args));
  assert.notEqual(
    deriveProducerEventId(args),
    deriveProducerEventId({ ...args, parts: ['shell', 'yarn build'] })
  );
  // A different session is a different event even with identical content: two agents running
  // the same command are two things that happened.
  assert.notEqual(
    deriveProducerEventId(args),
    deriveProducerEventId({ ...args, nativeSessionId: 'sess-2' })
  );
});

test('envelope: sealPayload drops anything not on the allowlist', () => {
  const sealed = sealPayload({
    tool: 'shell',
    detail: 'yarn test',
    // A codec bug or a malicious codec cannot widen this: the seal copies named keys only.
    ...({ rawInput: { content: 'secrets' }, transcriptPath: '/tmp/t.jsonl' } as never)
  });
  assert.deepEqual(Object.keys(sealed).sort(), ['detail', 'tool']);
});

/**
 * The waist test: one codec spec, two harness shapes, the same envelope.
 *
 * These two payloads are the actual native shapes — a Claude `PostToolUse` hook body and an
 * OpenCode control-plane tool part. If both produce the same normalized event, the abstraction
 * is in the right place. If they did not, the module would be a Claude adapter with extra
 * indirection.
 */
const CLAUDE_CODEC: CodecSpec = {
  codecVersion: 1,
  adapter: 'claude',
  eventNamePath: 'hook_event_name',
  nativeSessionPaths: ['session_id'],
  projectRootPaths: ['cwd'],
  events: [
    {
      native: 'PostToolUse',
      kind: 'tool.completed',
      origin: 'agent',
      toolPath: 'tool_name',
      inputPath: 'tool_input',
      callIdPath: 'tool_use_id',
      fileEditKind: 'file.edited'
    },
    { native: 'UserPromptSubmit', kind: 'prompt.submitted', origin: 'user', promptPath: 'prompt' }
  ]
};

const OPENCODE_CODEC: CodecSpec = {
  codecVersion: 1,
  adapter: 'opencode',
  nativeSessionPaths: ['properties.sessionID'],
  projectRootPaths: ['properties.cwd'],
  events: [
    {
      native: 'message.part.updated',
      kind: 'tool.completed',
      origin: 'agent',
      toolPath: 'properties.part.tool',
      inputPath: 'properties.part.state.input',
      callIdPath: 'properties.part.callID',
      outcomePath: 'properties.part.state.status',
      fileEditKind: 'file.edited'
    }
  ]
};

test('codec: the same normalized event comes out of a callback and a control plane', () => {
  const claude = normalizeNativeEvent({
    codec: CLAUDE_CODEC,
    payload: {
      hook_event_name: 'PostToolUse',
      session_id: 'sess-claude',
      cwd: '/repo',
      tool_name: 'Bash',
      tool_use_id: 'call-1',
      tool_input: { command: 'yarn test' }
    },
    occurredAt: '2026-08-01T00:00:00.000Z'
  });
  const opencode = normalizeNativeEvent({
    codec: OPENCODE_CODEC,
    payload: {
      properties: {
        sessionID: 'sess-opencode',
        cwd: '/repo',
        part: {
          tool: 'bash',
          callID: 'call-1',
          state: { status: 'completed', input: { command: 'yarn test' } }
        }
      }
    },
    nativeEventName: 'message.part.updated',
    occurredAt: '2026-08-01T00:00:00.000Z'
  });

  assert.ok(claude && opencode);
  assert.equal(claude.kind, 'tool.completed');
  assert.equal(opencode.kind, 'tool.completed');
  assert.equal(claude.summary, opencode.summary);
  assert.equal(claude.payload.tool, 'shell');
  assert.equal(opencode.payload.tool, 'shell');
  assert.equal(claude.payload.detail, 'yarn test');
  assert.equal(opencode.payload.detail, 'yarn test');
  assert.equal(opencode.payload.outcome, 'ok');
  // Different sessions, so different ids — the events are the same *shape*, not the same event.
  assert.notEqual(claude.eventId, opencode.eventId);
});

test('codec: a file-editing tool becomes a file.edited event with a repo-relative path', () => {
  const event = normalizeNativeEvent({
    codec: CLAUDE_CODEC,
    payload: {
      hook_event_name: 'PostToolUse',
      session_id: 'sess-claude',
      cwd: '/repo',
      tool_name: 'Write',
      tool_input: { file_path: '/repo/src/app.ts', content: 'never transmitted' }
    },
    occurredAt: '2026-08-01T00:00:00.000Z'
  });
  assert.equal(event?.kind, 'file.edited');
  assert.deepEqual(event?.payload.paths, ['src/app.ts']);
  assert.ok(!JSON.stringify(event).includes('never transmitted'));
});

test('codec: prompt text is persisted in full but still redacted', () => {
  const event = normalizeNativeEvent({
    codec: CLAUDE_CODEC,
    payload: {
      hook_event_name: 'UserPromptSubmit',
      session_id: 'sess-claude',
      prompt: 'deploy with token out_abcdefgh123456789 please'
    },
    occurredAt: '2026-08-01T00:00:00.000Z'
  });
  assert.equal(event?.kind, 'prompt.submitted');
  assert.equal(event?.payload.promptText, 'deploy with token [redacted] please');
  assert.equal(event?.origin, 'user');
});

test('codec: an unmapped native event is silence, not an error', () => {
  const event = normalizeNativeEvent({
    codec: CLAUDE_CODEC,
    payload: { hook_event_name: 'Notification', session_id: 'sess-claude' },
    occurredAt: '2026-08-01T00:00:00.000Z'
  });
  assert.equal(event, null);
});

test('codec: an empty prompt produces no event', () => {
  const event = normalizeNativeEvent({
    codec: CLAUDE_CODEC,
    payload: { hook_event_name: 'UserPromptSubmit', session_id: 's', prompt: '   ' },
    occurredAt: '2026-08-01T00:00:00.000Z'
  });
  assert.equal(event, null);
});

test('codec: replaying the identical native payload yields the identical event id', () => {
  const payload = {
    hook_event_name: 'PostToolUse',
    session_id: 'sess-claude',
    cwd: '/repo',
    tool_name: 'Bash',
    tool_use_id: 'call-9',
    tool_input: { command: 'ls' }
  };
  const first = normalizeNativeEvent({
    codec: CLAUDE_CODEC,
    payload,
    occurredAt: '2026-08-01T00:00:00.000Z'
  });
  // A retried hook fires later; the timestamp differs and the id must not.
  const replay = normalizeNativeEvent({
    codec: CLAUDE_CODEC,
    payload,
    occurredAt: '2026-08-01T00:05:00.000Z'
  });
  assert.equal(first?.eventId, replay?.eventId);
});
