import { config as loadDotenv } from 'dotenv';
import { app, BrowserWindow } from 'electron';
import fs from 'fs';
import path from 'path';

import { registerAppIpc } from './ipc/app';
import { registerSupabaseIpc } from './ipc/supabase';
import { registerTerminalIpc } from './ipc/terminal';
import { AppUpdaterService } from './services/app-updater';
import { findFreePort, startNextServer, stopNextServer } from './services/next-server';
import { SupabaseManager } from './services/supabase-manager';

// Baked-in production env vars (generated by scripts/embed-prod-env.mjs before build).
// Falls back to an empty object if the file doesn't exist (e.g. in dev or CI without the script).
let PROD_ENV: Record<string, string> = {};
try {
  // Dynamic import so missing file doesn't crash the module load
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const generated = require('./_prod-env.generated');
  PROD_ENV = generated.PROD_ENV ?? {};
} catch {
  // Not present — either dev build or script wasn't run
}

const isDev = !app.isPackaged;
let mainWindow: BrowserWindow | null = null;
const supabaseManager = new SupabaseManager();
const appUpdater = new AppUpdaterService({
  isPackaged: app.isPackaged,
  currentVersion: app.getVersion()
});

function loadLocalEnvForPackagedRuns() {
  if (isDev) return;

  // 1. Apply baked-in production vars first (lowest precedence — anything
  //    already in process.env or loaded by a file below will win).
  for (const [key, value] of Object.entries(PROD_ENV)) {
    if (!process.env[key]) {
      process.env[key] = value;
    }
  }

  // 2. Allow per-machine overrides via a .env file in the userData directory
  //    (~/Library/Application Support/Overlord/ on macOS).
  //    This lets operators override individual keys without rebuilding.
  const userDataDir = app.getPath('userData');
  const envFiles = ['.env.local', '.env'];

  for (const envFile of envFiles) {
    const envPath = path.join(userDataDir, envFile);
    if (!fs.existsSync(envPath)) continue;

    const result = loadDotenv({ path: envPath, override: false });
    if (result.error) {
      console.error(`[env] Failed to load ${envFile}:`, result.error);
    } else {
      console.warn(`[env] Loaded ${envFile} from ${envPath}`);
    }
  }
}

function createWindow(port: number) {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 900,
    minHeight: 600,
    center: true,
    titleBarStyle: 'hiddenInset',
    trafficLightPosition: { x: 14, y: 14 },
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false
    }
  });

  mainWindow.loadURL(`http://localhost:${port}`);

  if (isDev) {
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  }

  mainWindow.on('closed', () => {
    mainWindow = null;
    appUpdater.setMainWindow(null);
  });

  appUpdater.setMainWindow(mainWindow);
}

app.whenReady().then(async () => {
  loadLocalEnvForPackagedRuns();

  // Start local Supabase only in dev — production uses Supabase Cloud
  if (isDev) {
    try {
      await supabaseManager.start();
    } catch (err) {
      console.error('Failed to start Supabase:', err);
      // Continue anyway — user may have it running already
    }
  }

  // In dev the Next.js dev server runs separately on its own port (default 3000).
  // In production we start the standalone server on a free port to avoid conflicts
  // with anything else the user has running on their machine.
  const port = isDev ? 3000 : await findFreePort();

  if (!isDev) {
    // Expose the chosen port so agent-launcher and any other code reads it correctly.
    process.env.PLATFORM_URL = `http://localhost:${port}`;
    await startNextServer(port);
  }

  // Register IPC handlers
  registerTerminalIpc();
  registerSupabaseIpc(supabaseManager);
  registerAppIpc({ appUpdater });

  createWindow(port);
  appUpdater.initialize();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow(port);
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('before-quit', async () => {
  if (isDev) {
    try {
      await supabaseManager.stop();
    } catch {
      // Best-effort cleanup
    }
  }
  if (!isDev) {
    stopNextServer();
  }
});
