import {
  Activity,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  BookOpen,
  Bot,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleEllipsis,
  CirclePlus,
  CircleX,
  Clock,
  Cloud,
  CloudUpload,
  Construction,
  Copy,
  ExternalLink,
  File,
  FileText,
  Filter,
  Folder,
  FolderOpen,
  GitBranch,
  Globe,
  GripVertical,
  Image,
  Images,
  Info,
  Key,
  List,
  LogOut,
  type LucideIcon,
  type LucideProps,
  Menu,
  MessageSquareMore,
  Monitor,
  Moon,
  MoreHorizontal,
  Newspaper,
  Paperclip,
  Play,
  Plus,
  RefreshCw,
  Save,
  Search,
  Server,
  Settings,
  Shield,
  Smartphone,
  Square,
  Sun,
  Tag,
  Terminal,
  Ticket,
  Trash2,
  TriangleAlert,
  UserRound,
  X
} from 'lucide-react-native';
import type { ImageSourcePropType } from 'react-native';

import newspaperTabIcon from '../assets/lucide-tabs/newspaper.png';
import ticketTabIcon from '../assets/lucide-tabs/ticket.png';
import userRoundTabIcon from '../assets/lucide-tabs/userRound.png';

export const glyphMap = {
  add: 'plus',
  'add-circle-outline': 'circle-plus',
  'alert-circle-outline': 'circle-alert',
  'arrow-up': 'arrow-up',
  'arrow-forward': 'arrow-right',
  'book-outline': 'book-open',
  'build-outline': 'construction',
  'calendar-outline': 'calendar',
  'camera-outline': 'camera',
  'chatbox-ellipses-outline': 'message-square-more',
  checkmark: 'check',
  'checkmark-circle': 'check-circle',
  'checkmark-circle-outline': 'circle-check',
  'chevron-down': 'chevron-down',
  'chevron-expand-outline': 'chevrons-up-down',
  'chevron-back': 'chevron-left',
  'chevron-forward': 'chevron-right',
  'chevron-up': 'chevron-up',
  close: 'x',
  'close-circle': 'circle-x',
  'close-outline': 'x',
  'cloud-outline': 'cloud',
  'cloud-upload-outline': 'cloud-upload',
  'copy-outline': 'copy',
  'desktop-outline': 'monitor',
  'document-attach-outline': 'paperclip',
  'document-outline': 'file',
  'document-text-outline': 'file-text',
  'ellipsis-horizontal': 'more-horizontal',
  'ellipsis-horizontal-circle-outline': 'circle-ellipsis',
  'folder-open-outline': 'folder-open',
  'folder-outline': 'folder',
  'funnel-outline': 'filter',
  'git-network-outline': 'git-branch',
  'git-branch-outline': 'git-branch',
  'globe-outline': 'globe',
  'image-outline': 'image',
  'information-circle-outline': 'info',
  'hardware-chip-outline': 'bot',
  'images-outline': 'images',
  'key-outline': 'key',
  'list-outline': 'list',
  'log-out-outline': 'log-out',
  'menu-outline': 'menu',
  'moon-outline': 'moon',
  'newspaper-outline': 'newspaper',
  'open-outline': 'external-link',
  person: 'user-round',
  'person-outline': 'user-round',
  play: 'play',
  'pulse-outline': 'activity',
  'radio-button-on': 'circle-dot',
  'radio-button-off': 'circle',
  'reorder-three-outline': 'grip-vertical',
  'refresh-outline': 'refresh-cw',
  'save-outline': 'save',
  search: 'search',
  'sunny-outline': 'sun',
  'phone-portrait-outline': 'smartphone',
  'pricetag-outline': 'tag',
  server: 'server',
  'server-outline': 'server',
  'settings-outline': 'settings',
  'shield-outline': 'shield',
  'stop-outline': 'square',
  'warning-outline': 'triangle-alert',
  'swap-vertical-outline': 'arrow-up-down',
  'terminal-outline': 'terminal',
  'ticket-outline': 'ticket',
  'time-outline': 'clock',
  'trash-outline': 'trash-2'
} as const;

export type IoniconName = keyof typeof glyphMap;

type IconComponent = LucideIcon;

const iconMap: Record<IoniconName, IconComponent> = {
  add: Plus,
  'add-circle-outline': CirclePlus,
  'alert-circle-outline': CircleAlert,
  'arrow-up': ArrowUp,
  'arrow-forward': ArrowRight,
  'book-outline': BookOpen,
  'build-outline': Construction,
  'calendar-outline': Calendar,
  'camera-outline': Camera,
  'chatbox-ellipses-outline': MessageSquareMore,
  checkmark: Check,
  'checkmark-circle': CheckCircle,
  'checkmark-circle-outline': CircleCheck,
  'chevron-down': ChevronDown,
  'chevron-back': ChevronLeft,
  'chevron-expand-outline': ChevronsUpDown,
  'chevron-forward': ChevronRight,
  'chevron-up': ChevronUp,
  close: X,
  'close-circle': CircleX,
  'close-outline': X,
  'cloud-outline': Cloud,
  'cloud-upload-outline': CloudUpload,
  'copy-outline': Copy,
  'desktop-outline': Monitor,
  'document-attach-outline': Paperclip,
  'document-outline': File,
  'document-text-outline': FileText,
  'ellipsis-horizontal': MoreHorizontal,
  'ellipsis-horizontal-circle-outline': CircleEllipsis,
  'folder-open-outline': FolderOpen,
  'folder-outline': Folder,
  'funnel-outline': Filter,
  'git-network-outline': GitBranch,
  'git-branch-outline': GitBranch,
  'globe-outline': Globe,
  'image-outline': Image,
  'information-circle-outline': Info,
  'hardware-chip-outline': Bot,
  'images-outline': Images,
  'key-outline': Key,
  'list-outline': List,
  'log-out-outline': LogOut,
  'menu-outline': Menu,
  'newspaper-outline': Newspaper,
  'open-outline': ExternalLink,
  person: UserRound,
  'person-outline': UserRound,
  play: Play,
  'pulse-outline': Activity,
  'radio-button-on': CircleDot,
  'radio-button-off': Circle,
  'phone-portrait-outline': Smartphone,
  'pricetag-outline': Tag,
  'reorder-three-outline': GripVertical,
  'refresh-outline': RefreshCw,
  'save-outline': Save,
  search: Search,
  'moon-outline': Moon,
  'sunny-outline': Sun,
  server: Server,
  'server-outline': Server,
  'settings-outline': Settings,
  'shield-outline': Shield,
  'stop-outline': Square,
  'warning-outline': TriangleAlert,
  'swap-vertical-outline': ArrowUpDown,
  'terminal-outline': Terminal,
  'ticket-outline': Ticket,
  'time-outline': Clock,
  'trash-outline': Trash2
};

const tabIconSources: Partial<Record<IoniconName, ImageSourcePropType>> = {
  'newspaper-outline': newspaperTabIcon,
  'ticket-outline': ticketTabIcon,
  person: userRoundTabIcon,
  'person-outline': userRoundTabIcon
};

function IoniconsBase({ name, ...props }: LucideProps & { name: IoniconName }) {
  const Icon = iconMap[name];
  if (!Icon) {
    if (__DEV__) {
      console.warn(`[Ionicons] Missing Lucide mapping for "${name}"`);
    }
    return <CircleAlert {...props} />;
  }

  return <Icon {...props} />;
}

export const Ionicons = Object.assign(IoniconsBase, {
  glyphMap,
  getImageSource: async (name: IoniconName) => {
    return tabIconSources[name] ?? null;
  }
});
