slug: creating-types
name: creating-types
description: How to create types using the supabase database schema
tags: []
compat: []
sha256: 2d9f2823f8bae1eafe35de3c515d50431a151f8f740bb67d11a01ced4db312dd
