// Production CLI build: typecheck-friendly tsc emit for tests, then esbuild bundles
// `src/index.ts` (and its dependency graph, including `@overlord/core`) into a single
// self-contained `dist/index.js` for npm publish and the desktop app staging dir.
import { spawnSync } from 'node:child_process';
import { cpSync, readFileSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const cliRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(cliRoot, '..');
const tsc = path.join(repoRoot, 'node_modules', '.bin', 'tsc');
const outfile = path.join(cliRoot, 'dist', 'index.js');

// Native addons cannot be inlined. Everything else the CLI graph actually
// imports — including private workspace packages such as `@overlord/database`
// display-id helpers, `yaml`, and `smol-toml` — must land in `dist/index.js`.
// The published tarball and the desktop staging dir ship that file without
// workspace `node_modules`, so an externalized `@overlord/*` import crashes
// Node with ERR_MODULE_NOT_FOUND on every `ovld` invocation.
const bundleExternals = ['better-sqlite3'];

function run(command, args, cwd = cliRoot) {
  const result = spawnSync(command, args, { cwd, stdio: 'inherit' });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function collectBarePackageImports({ source }) {
  const specifiers = [];
  for (const line of source.split('\n')) {
    const match =
      /^import\s+['"]([^'"]+)['"]/.exec(line) ??
      /^import\s+.+\sfrom\s+['"]([^'"]+)['"]/.exec(line) ??
      /^}\s*from\s+['"]([^'"]+)['"]/.exec(line);
    if (!match) continue;
    const specifier = match[1];
    if (!specifier.startsWith('node:') && !specifier.startsWith('.')) {
      specifiers.push(specifier);
    }
  }
  return [...new Set(specifiers)];
}

function assertBundleHasNoPackageImports({ bundlePath }) {
  const source = readFileSync(bundlePath, 'utf8');
  const leftover = [...new Set(collectBarePackageImports({ source }))];
  if (leftover.length === 0) return;

  console.error(
    `cli/dist/index.js still imports packages that the published CLI does not install:\n` +
      leftover.map(specifier => `  - ${specifier}`).join('\n') +
      '\nBundle those packages (or stop importing them) instead of marking them external.'
  );
  process.exit(1);
}

rmSync(path.join(cliRoot, 'dist'), { recursive: true, force: true });

run('yarn', ['workspace', '@overlord/database', 'build'], repoRoot);
run('yarn', ['workspace', '@overlord/core', 'build'], repoRoot);
run('yarn', ['workspace', '@overlord/contract', 'build'], repoRoot);

// Per-module emit for unit tests that import individual `dist/*.js` modules.
run(tsc, ['--project', 'tsconfig.build.json'], cliRoot);

await build({
  entryPoints: [path.join(cliRoot, 'src', 'index.ts')],
  outfile,
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  external: bundleExternals,
  sourcemap: true,
  logLevel: 'info',
  banner: {
    // `yaml` ships its Node build as CommonJS and dynamically loads Node
    // built-ins such as `process` and `buffer`. In an ESM bundle esbuild's
    // generated dynamic-require shim otherwise throws before parsing YAML.
    // Keep the dependency bundled while giving that shim a Node resolver.
    js:
      "import { createRequire } from 'node:module';\n" +
      "const require = createRequire(import.meta.url);\n" +
      '// Overlord CLI bundle — generated by cli/scripts/build.mjs. Do not edit.'
  }
});

assertBundleHasNoPackageImports({ bundlePath: outfile });

cpSync(path.join(repoRoot, 'connectors'), path.join(cliRoot, 'dist', 'connectors'), {
  recursive: true,
  filter: source => path.basename(source) !== '.DS_Store'
});

cpSync(
  path.join(repoRoot, 'contract', 'conformance-manifest.schema.yaml'),
  path.join(cliRoot, 'dist', 'contract', 'conformance-manifest.schema.yaml')
);

console.log('Bundled cli/dist/index.js (includes @overlord/core) for npm/desktop runtime.');
