#!/usr/bin/env node
/**
 * Unified Electron production build script.
 *
 * Why this exists:
 *   NEXT_PUBLIC_* variables (Supabase URL, publishable key, site URL) are baked
 *   into the Next.js client bundle at build time — they are NOT runtime-patchable.
 *   `electron/main.ts` applies `.env.prod` to `process.env` at startup, which fixes
 *   server-side code (API routes, server components), but the React client bundle
 *   has already been compiled with whatever env was active during `next build`.
 *
 *   This script reads `.env.prod`, generates `electron/_prod-env.generated.ts` for
 *   the main-process runtime patch, then passes the same vars as the actual process
 *   environment when spawning `next build`, so the client bundle gets the correct
 *   production Supabase URL and keys compiled in.
 *
 * Usage:
 *   node scripts/electron-build.mjs          → full build + electron-builder (DMG/pkg)
 *   node scripts/electron-build.mjs --dir    → build + unpackaged app dir only (faster, for testing)
 */

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const isDirMode = process.argv.includes('--dir');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function parseDotenv(content) {
  const vars = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();
    // Strip surrounding quotes
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  }
  return vars;
}

function run(cmd, env) {
  console.log(`\n\x1b[36m>\x1b[0m ${cmd}`);
  const result = spawnSync(cmd, {
    shell: true,
    stdio: 'inherit',
    env: env ?? process.env,
    cwd: ROOT
  });
  if (result.status !== 0) {
    console.error(`\x1b[31m[build] Command failed: ${cmd}\x1b[0m`);
    process.exit(result.status ?? 1);
  }
}

// ---------------------------------------------------------------------------
// Step 1 — Read .env.prod
// ---------------------------------------------------------------------------

const envFile = resolve(ROOT, '.env.prod');
let prodEnvVars;
try {
  prodEnvVars = parseDotenv(readFileSync(envFile, 'utf8'));
} catch {
  console.error(`\x1b[31m[build] ERROR: .env.prod not found at ${envFile}\x1b[0m`);
  console.error('       Create it with your production Supabase credentials before building.');
  process.exit(1);
}

console.log(
  `[build] Loaded ${Object.keys(prodEnvVars).length} vars from .env.prod: ${Object.keys(prodEnvVars).join(', ')}`
);

// ---------------------------------------------------------------------------
// Step 2 — Generate electron/_prod-env.generated.ts  (runtime main-process patch)
// ---------------------------------------------------------------------------

const entries = Object.entries(prodEnvVars)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join('\n');

const generatedTs = `// AUTO-GENERATED by scripts/electron-build.mjs — DO NOT COMMIT\n// Run \`node scripts/electron-build.mjs\` before building the Electron app.\n\nexport const PROD_ENV: Record<string, string> = {\n${entries}\n};\n`;

const outFile = resolve(ROOT, 'electron', '_prod-env.generated.ts');
writeFileSync(outFile, generatedTs, 'utf8');
console.log('[build] Written electron/_prod-env.generated.ts');

// ---------------------------------------------------------------------------
// Step 3 — next build  (with prod env so NEXT_PUBLIC_* are baked in correctly)
// ---------------------------------------------------------------------------

const buildEnv = {
  ...process.env,
  ...prodEnvVars,
  NODE_ENV: 'production'
};

run('yarn next build', buildEnv);

// ---------------------------------------------------------------------------
// Step 4 — Copy Next.js static assets into standalone output
// ---------------------------------------------------------------------------

run('cp -r .next/static .next/standalone/.next/static');

// ---------------------------------------------------------------------------
// Step 5 — Compile Electron main-process TypeScript
// ---------------------------------------------------------------------------

run('yarn tsc -p electron/tsconfig.json');

// ---------------------------------------------------------------------------
// Step 6 — electron-builder
// ---------------------------------------------------------------------------

run(`yarn electron-builder${isDirMode ? ' --dir' : ''}`);
