create extension if not exists pgcrypto;

create type public.ticket_status as enum (
  'draft',
  'review',
  'refine',
  'execute',
  'deliver',
  'complete',
  'blocked',
  'cancelled'
);

create type public.ticket_priority as enum ('low', 'medium', 'high', 'urgent');

create type public.connection_method as enum (
  'mcp',
  'cli',
  'rest',
  'chatgpt',
  'claude_app',
  'claude_code',
  'other'
);

create type public.session_state as enum (
  'attached',
  'idle',
  'blocked',
  'completed',
  'disconnected'
);

create type public.ticket_event_type as enum (
  'system',
  'question',
  'answer',
  'update',
  'context_write',
  'context_read',
  'artifact',
  'deliver',
  'status_change',
  'alert'
);

create table if not exists public.tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_sequence bigint generated by default as identity unique,
  ticket_number text generated always as ('TICKET-' || lpad(ticket_sequence::text, 4, '0')) stored,
  title text not null,
  objective text not null,
  context text not null default '',
  constraints text not null default '',
  available_tools text not null default '',
  acceptance_criteria text not null default '',
  output_format text not null default '',
  assigned_agent text,
  priority public.ticket_priority not null default 'medium',
  status public.ticket_status not null default 'draft',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.agent_sessions (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  agent_identifier text not null,
  connection_method public.connection_method not null default 'rest',
  session_state public.session_state not null default 'attached',
  session_key uuid not null unique default gen_random_uuid(),
  metadata jsonb not null default '{}'::jsonb,
  heartbeat_at timestamptz not null default timezone('utc', now()),
  attached_at timestamptz not null default timezone('utc', now()),
  detached_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.ticket_events (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  session_id uuid references public.agent_sessions(id) on delete set null,
  event_type public.ticket_event_type not null default 'update',
  phase public.ticket_status,
  summary text,
  payload jsonb not null default '{}'::jsonb,
  is_blocking boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.shared_state (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid references public.tickets(id) on delete cascade,
  session_id uuid references public.agent_sessions(id) on delete set null,
  state_key text not null,
  state_value jsonb not null,
  tags text[] not null default '{}'::text[],
  source text not null default 'agent',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.artifacts (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  event_id uuid references public.ticket_events(id) on delete set null,
  session_id uuid references public.agent_sessions(id) on delete set null,
  artifact_type text not null,
  label text not null,
  uri text,
  content text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.connections (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  provider text not null,
  display_name text not null,
  config jsonb not null default '{}'::jsonb,
  is_default boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists tickets_status_idx on public.tickets(status);
create index if not exists tickets_updated_idx on public.tickets(updated_at desc);
create index if not exists agent_sessions_ticket_id_idx on public.agent_sessions(ticket_id);
create index if not exists agent_sessions_key_idx on public.agent_sessions(session_key);
create index if not exists ticket_events_ticket_created_idx on public.ticket_events(ticket_id, created_at desc);
create index if not exists shared_state_ticket_created_idx on public.shared_state(ticket_id, created_at desc);
create index if not exists shared_state_key_idx on public.shared_state(state_key);
create index if not exists artifacts_ticket_created_idx on public.artifacts(ticket_id, created_at desc);
create index if not exists connections_owner_idx on public.connections(owner_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_tickets_updated_at on public.tickets;
create trigger set_tickets_updated_at
before update on public.tickets
for each row
execute function public.set_updated_at();

drop trigger if exists set_agent_sessions_updated_at on public.agent_sessions;
create trigger set_agent_sessions_updated_at
before update on public.agent_sessions
for each row
execute function public.set_updated_at();

drop trigger if exists set_connections_updated_at on public.connections;
create trigger set_connections_updated_at
before update on public.connections
for each row
execute function public.set_updated_at();

alter table public.tickets enable row level security;
alter table public.agent_sessions enable row level security;
alter table public.ticket_events enable row level security;
alter table public.shared_state enable row level security;
alter table public.artifacts enable row level security;
alter table public.connections enable row level security;

create policy "tickets_select_local" on public.tickets
for select to anon, authenticated
using (true);

create policy "tickets_insert_local" on public.tickets
for insert to anon, authenticated
with check (true);

create policy "tickets_update_local" on public.tickets
for update to anon, authenticated
using (true)
with check (true);

create policy "tickets_delete_local" on public.tickets
for delete to anon, authenticated
using (true);

create policy "agent_sessions_select_local" on public.agent_sessions
for select to anon, authenticated
using (true);

create policy "agent_sessions_insert_local" on public.agent_sessions
for insert to anon, authenticated
with check (true);

create policy "agent_sessions_update_local" on public.agent_sessions
for update to anon, authenticated
using (true)
with check (true);

create policy "agent_sessions_delete_local" on public.agent_sessions
for delete to anon, authenticated
using (true);

create policy "ticket_events_select_local" on public.ticket_events
for select to anon, authenticated
using (true);

create policy "ticket_events_insert_local" on public.ticket_events
for insert to anon, authenticated
with check (true);

create policy "ticket_events_update_local" on public.ticket_events
for update to anon, authenticated
using (true)
with check (true);

create policy "ticket_events_delete_local" on public.ticket_events
for delete to anon, authenticated
using (true);

create policy "shared_state_select_local" on public.shared_state
for select to anon, authenticated
using (true);

create policy "shared_state_insert_local" on public.shared_state
for insert to anon, authenticated
with check (true);

create policy "shared_state_update_local" on public.shared_state
for update to anon, authenticated
using (true)
with check (true);

create policy "shared_state_delete_local" on public.shared_state
for delete to anon, authenticated
using (true);

create policy "artifacts_select_local" on public.artifacts
for select to anon, authenticated
using (true);

create policy "artifacts_insert_local" on public.artifacts
for insert to anon, authenticated
with check (true);

create policy "artifacts_update_local" on public.artifacts
for update to anon, authenticated
using (true)
with check (true);

create policy "artifacts_delete_local" on public.artifacts
for delete to anon, authenticated
using (true);

create policy "connections_select_local" on public.connections
for select to anon, authenticated
using (true);

create policy "connections_insert_local" on public.connections
for insert to anon, authenticated
with check (true);

create policy "connections_update_local" on public.connections
for update to anon, authenticated
using (true)
with check (true);

create policy "connections_delete_local" on public.connections
for delete to anon, authenticated
using (true);
