create table "public"."schedule" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
  "period_type" text not null default 'd'::text,
  "period_interval" smallint not null default 1,
  "weeks_of_month" smallint[],
  "days_of_month" smallint[],
  "start_date" timestamp with time zone,
  "timezone" text not null,
  "days_of_week" jsonb,
  "name" text,
  "organization_id" integer not null
);

alter table "public"."schedule" enable row level security;

create unique index "schedule_pkey" on "public"."schedule" using btree ("id");
create unique index "schedule_id_organization_id_key" on "public"."schedule" using btree ("id", "organization_id");
create index "idx_schedule_organization_id" on "public"."schedule" using btree ("organization_id");
create index "idx_schedule_start_date" on "public"."schedule" using btree ("start_date");

alter table "public"."schedule"
  add constraint "schedule_pkey" primary key using index "schedule_pkey";

alter table "public"."schedule"
  add constraint "schedule_id_organization_id_key" unique using index "schedule_id_organization_id_key";

alter table "public"."schedule"
  add constraint "schedule_organization_id_fkey"
  foreign key ("organization_id") references "public"."organizations"("id")
  on delete cascade not valid;

alter table "public"."schedule"
  validate constraint "schedule_organization_id_fkey";

create or replace function "public"."schedule_days_of_week_is_valid"(payload jsonb)
returns boolean
language sql
immutable
as $$
  select
    payload is null
    or (
      jsonb_typeof(payload) = 'array'
      and not exists (
        select 1
        from jsonb_array_elements(payload) as day_entry
        where jsonb_typeof(day_entry) <> 'object'
          or jsonb_typeof(day_entry->'times') <> 'array'
          or coalesce(nullif(day_entry->>'dayNum', ''), nullif(day_entry->>'day_num', '')) is null
          or (coalesce(nullif(day_entry->>'dayNum', ''), nullif(day_entry->>'day_num', ''))) !~ '^[0-6]$'
          or exists (
            select 1
            from jsonb_array_elements(day_entry->'times') as time_entry
            where jsonb_typeof(time_entry) <> 'string'
              or (time_entry #>> '{}') !~ '^([01]\d|2[0-3]):[0-5]\d(:[0-5]\d)?$'
          )
      )
    );
$$;

create or replace function "public"."schedule_smallint_array_between"(
  payload smallint[],
  min_value smallint,
  max_value smallint
)
returns boolean
language sql
immutable
as $$
  select
    payload is null
    or coalesce(
      (
        select bool_and(value between min_value and max_value)
        from unnest(payload) as value
      ),
      true
    );
$$;

alter table "public"."schedule"
  add constraint "schedule_period_type_check"
  check ("period_type" = any (array['d'::text, 'w'::text, 'm'::text]));

alter table "public"."schedule"
  add constraint "schedule_period_interval_check"
  check ("period_interval" > 0);

alter table "public"."schedule"
  add constraint "schedule_days_of_month_check"
  check (
    "public"."schedule_smallint_array_between"(
      "days_of_month",
      1::smallint,
      32::smallint
    )
  );

alter table "public"."schedule"
  add constraint "schedule_weeks_of_month_check"
  check (
    "public"."schedule_smallint_array_between"(
      "weeks_of_month",
      1::smallint,
      5::smallint
    )
  );

alter table "public"."schedule"
  add constraint "schedule_days_of_week_shape_check"
  check ("public"."schedule_days_of_week_is_valid"("days_of_week"));

alter table "public"."schedule"
  add constraint "schedule_monthly_shape_check"
  check (
    "period_type" <> 'm'
    or coalesce(array_length("days_of_month", 1), 0) > 0
    or (
      coalesce(array_length("weeks_of_month", 1), 0) > 0
      and coalesce(case when "days_of_week" is null then 0 else jsonb_array_length("days_of_week") end, 0) > 0
    )
  );

alter table "public"."tickets"
  add column "due_datetime" timestamp with time zone,
  add column "schedule_id" bigint;

create index "tickets_due_datetime_idx" on "public"."tickets" using btree ("organization_id", "due_datetime");
create index "tickets_schedule_id_idx" on "public"."tickets" using btree ("schedule_id");

alter table "public"."tickets"
  add constraint "tickets_schedule_org_fkey"
  foreign key ("schedule_id", "organization_id") references "public"."schedule"("id", "organization_id")
  on update cascade
  on delete set null not valid;

alter table "public"."tickets"
  validate constraint "tickets_schedule_org_fkey";

grant delete on table "public"."schedule" to "anon";
grant insert on table "public"."schedule" to "anon";
grant references on table "public"."schedule" to "anon";
grant select on table "public"."schedule" to "anon";
grant trigger on table "public"."schedule" to "anon";
grant truncate on table "public"."schedule" to "anon";
grant update on table "public"."schedule" to "anon";
grant delete on table "public"."schedule" to "authenticated";
grant insert on table "public"."schedule" to "authenticated";
grant references on table "public"."schedule" to "authenticated";
grant select on table "public"."schedule" to "authenticated";
grant trigger on table "public"."schedule" to "authenticated";
grant truncate on table "public"."schedule" to "authenticated";
grant update on table "public"."schedule" to "authenticated";
grant delete on table "public"."schedule" to "service_role";
grant insert on table "public"."schedule" to "service_role";
grant references on table "public"."schedule" to "service_role";
grant select on table "public"."schedule" to "service_role";
grant trigger on table "public"."schedule" to "service_role";
grant truncate on table "public"."schedule" to "service_role";
grant update on table "public"."schedule" to "service_role";

create policy "schedule_delete_manager_plus"
on "public"."schedule"
as permissive
for delete
to authenticated
using (public.has_org_role("organization_id", array['MANAGER'::public.organization_role, 'ADMIN'::public.organization_role]));

create policy "schedule_insert_agent_plus"
on "public"."schedule"
as permissive
for insert
to authenticated
with check (public.has_org_role("organization_id", array['AGENT'::public.organization_role, 'MANAGER'::public.organization_role, 'ADMIN'::public.organization_role]));

create policy "schedule_select_member"
on "public"."schedule"
as permissive
for select
to authenticated
using (public.is_org_member("organization_id"));

create policy "schedule_update_agent_plus"
on "public"."schedule"
as permissive
for update
to authenticated
using (public.has_org_role("organization_id", array['AGENT'::public.organization_role, 'MANAGER'::public.organization_role, 'ADMIN'::public.organization_role]))
with check (public.has_org_role("organization_id", array['AGENT'::public.organization_role, 'MANAGER'::public.organization_role, 'ADMIN'::public.organization_role]));
