create type "public"."connection_method" as enum ('mcp', 'cli', 'rest', 'chatgpt', 'claude_app', 'claude_code', 'other');

create type "public"."organization_role" as enum ('VIEWER', 'AGENT', 'MANAGER', 'ADMIN');

create type "public"."session_state" as enum ('attached', 'idle', 'blocked', 'completed', 'disconnected');

create type "public"."ticket_event_type" as enum ('system', 'question', 'answer', 'update', 'context_write', 'context_read', 'artifact', 'deliver', 'status_change', 'alert');

create type "public"."ticket_priority" as enum ('low', 'medium', 'high', 'urgent');

create type "public"."ticket_status_type" as enum ('draft', 'execute', 'review', 'complete');


  create table "public"."agent_sessions" (
    "id" uuid not null default gen_random_uuid(),
    "ticket_id" uuid not null,
    "agent_identifier" text not null,
    "connection_method" public.connection_method not null default 'rest'::public.connection_method,
    "session_state" public.session_state not null default 'attached'::public.session_state,
    "session_key" uuid not null default gen_random_uuid(),
    "metadata" jsonb not null default '{}'::jsonb,
    "heartbeat_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "attached_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "detached_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."agent_sessions" enable row level security;


  create table "public"."artifacts" (
    "id" uuid not null default gen_random_uuid(),
    "ticket_id" uuid not null,
    "event_id" uuid,
    "session_id" uuid,
    "artifact_type" text not null,
    "label" text not null,
    "uri" text,
    "content" text,
    "metadata" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."artifacts" enable row level security;


  create table "public"."connections" (
    "id" uuid not null default gen_random_uuid(),
    "owner_id" uuid,
    "provider" text not null,
    "display_name" text not null,
    "config" jsonb not null default '{}'::jsonb,
    "is_default" boolean not null default false,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."connections" enable row level security;


  create table "public"."members" (
    "organization_id" integer not null,
    "user_id" uuid not null,
    "role" public.organization_role not null default 'VIEWER'::public.organization_role,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."members" enable row level security;


  create table "public"."organizations" (
    "id" integer generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."organizations" enable row level security;


  create table "public"."shared_state" (
    "id" uuid not null default gen_random_uuid(),
    "ticket_id" uuid,
    "session_id" uuid,
    "state_key" text not null,
    "state_value" jsonb not null,
    "tags" text[] not null default '{}'::text[],
    "source" text not null default 'agent'::text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."shared_state" enable row level security;


  create table "public"."ticket_events" (
    "id" uuid not null default gen_random_uuid(),
    "ticket_id" uuid not null,
    "session_id" uuid,
    "event_type" public.ticket_event_type not null default 'update'::public.ticket_event_type,
    "phase" text,
    "summary" text,
    "payload" jsonb not null default '{}'::jsonb,
    "is_blocking" boolean not null default false,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."ticket_events" enable row level security;


  create table "public"."ticket_statuses" (
    "name" text not null,
    "status_type" public.ticket_status_type not null,
    "position" smallint not null default 0,
    "is_default" boolean not null default false,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "organization_id" integer not null
      );


alter table "public"."ticket_statuses" enable row level security;


  create table "public"."tickets" (
    "id" uuid not null default gen_random_uuid(),
    "ticket_sequence" bigint generated by default as identity not null,
    "ticket_number" text generated always as (('TICKET-'::text || lpad((ticket_sequence)::text, 4, '0'::text))) stored,
    "title" text not null,
    "objective" text not null,
    "context" text not null default ''::text,
    "constraints" text not null default ''::text,
    "available_tools" text not null default ''::text,
    "acceptance_criteria" text not null default ''::text,
    "output_format" text not null default ''::text,
    "assigned_agent" text,
    "priority" public.ticket_priority not null default 'medium'::public.ticket_priority,
    "status" text not null default 'draft'::text,
    "created_by" uuid not null default auth.uid(),
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "board_position" integer not null default 0,
    "organization_id" integer not null
      );


alter table "public"."tickets" enable row level security;

CREATE INDEX agent_sessions_key_idx ON public.agent_sessions USING btree (session_key);

CREATE UNIQUE INDEX agent_sessions_pkey ON public.agent_sessions USING btree (id);

CREATE UNIQUE INDEX agent_sessions_session_key_key ON public.agent_sessions USING btree (session_key);

CREATE INDEX agent_sessions_ticket_id_idx ON public.agent_sessions USING btree (ticket_id);

CREATE UNIQUE INDEX artifacts_pkey ON public.artifacts USING btree (id);

CREATE INDEX artifacts_ticket_created_idx ON public.artifacts USING btree (ticket_id, created_at DESC);

CREATE INDEX connections_owner_idx ON public.connections USING btree (owner_id);

CREATE UNIQUE INDEX connections_pkey ON public.connections USING btree (id);

CREATE INDEX members_organization_role_idx ON public.members USING btree (organization_id, role);

CREATE UNIQUE INDEX members_pkey ON public.members USING btree (organization_id, user_id);

CREATE INDEX members_user_id_idx ON public.members USING btree (user_id);

CREATE UNIQUE INDEX organizations_pkey ON public.organizations USING btree (id);

CREATE INDEX shared_state_key_idx ON public.shared_state USING btree (state_key);

CREATE UNIQUE INDEX shared_state_pkey ON public.shared_state USING btree (id);

CREATE INDEX shared_state_ticket_created_idx ON public.shared_state USING btree (ticket_id, created_at DESC);

CREATE UNIQUE INDEX ticket_events_pkey ON public.ticket_events USING btree (id);

CREATE INDEX ticket_events_ticket_created_idx ON public.ticket_events USING btree (ticket_id, created_at DESC);

CREATE INDEX ticket_statuses_organization_type_idx ON public.ticket_statuses USING btree (organization_id, status_type);

CREATE UNIQUE INDEX ticket_statuses_pkey ON public.ticket_statuses USING btree (organization_id, name);

CREATE INDEX tickets_board_position_idx ON public.tickets USING btree (board_position);

CREATE INDEX tickets_created_by_status_idx ON public.tickets USING btree (created_by, status);

CREATE INDEX tickets_organization_status_idx ON public.tickets USING btree (organization_id, status);

CREATE INDEX tickets_organization_updated_idx ON public.tickets USING btree (organization_id, updated_at DESC);

CREATE UNIQUE INDEX tickets_pkey ON public.tickets USING btree (id);

CREATE INDEX tickets_status_idx ON public.tickets USING btree (status);

CREATE UNIQUE INDEX tickets_ticket_sequence_key ON public.tickets USING btree (ticket_sequence);

CREATE INDEX tickets_updated_idx ON public.tickets USING btree (updated_at DESC);

alter table "public"."agent_sessions" add constraint "agent_sessions_pkey" PRIMARY KEY using index "agent_sessions_pkey";

alter table "public"."artifacts" add constraint "artifacts_pkey" PRIMARY KEY using index "artifacts_pkey";

alter table "public"."connections" add constraint "connections_pkey" PRIMARY KEY using index "connections_pkey";

alter table "public"."members" add constraint "members_pkey" PRIMARY KEY using index "members_pkey";

alter table "public"."organizations" add constraint "organizations_pkey" PRIMARY KEY using index "organizations_pkey";

alter table "public"."shared_state" add constraint "shared_state_pkey" PRIMARY KEY using index "shared_state_pkey";

alter table "public"."ticket_events" add constraint "ticket_events_pkey" PRIMARY KEY using index "ticket_events_pkey";

alter table "public"."ticket_statuses" add constraint "ticket_statuses_pkey" PRIMARY KEY using index "ticket_statuses_pkey";

alter table "public"."tickets" add constraint "tickets_pkey" PRIMARY KEY using index "tickets_pkey";

alter table "public"."agent_sessions" add constraint "agent_sessions_session_key_key" UNIQUE using index "agent_sessions_session_key_key";

alter table "public"."agent_sessions" add constraint "agent_sessions_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE not valid;

alter table "public"."agent_sessions" validate constraint "agent_sessions_ticket_id_fkey";

alter table "public"."artifacts" add constraint "artifacts_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.ticket_events(id) ON DELETE SET NULL not valid;

alter table "public"."artifacts" validate constraint "artifacts_event_id_fkey";

alter table "public"."artifacts" add constraint "artifacts_session_id_fkey" FOREIGN KEY (session_id) REFERENCES public.agent_sessions(id) ON DELETE SET NULL not valid;

alter table "public"."artifacts" validate constraint "artifacts_session_id_fkey";

alter table "public"."artifacts" add constraint "artifacts_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE not valid;

alter table "public"."artifacts" validate constraint "artifacts_ticket_id_fkey";

alter table "public"."connections" add constraint "connections_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."connections" validate constraint "connections_owner_id_fkey";

alter table "public"."members" add constraint "members_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE not valid;

alter table "public"."members" validate constraint "members_organization_id_fkey";

alter table "public"."members" add constraint "members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."members" validate constraint "members_user_id_fkey";

alter table "public"."shared_state" add constraint "shared_state_session_id_fkey" FOREIGN KEY (session_id) REFERENCES public.agent_sessions(id) ON DELETE SET NULL not valid;

alter table "public"."shared_state" validate constraint "shared_state_session_id_fkey";

alter table "public"."shared_state" add constraint "shared_state_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE not valid;

alter table "public"."shared_state" validate constraint "shared_state_ticket_id_fkey";

alter table "public"."ticket_events" add constraint "ticket_events_session_id_fkey" FOREIGN KEY (session_id) REFERENCES public.agent_sessions(id) ON DELETE SET NULL not valid;

alter table "public"."ticket_events" validate constraint "ticket_events_session_id_fkey";

alter table "public"."ticket_events" add constraint "ticket_events_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE not valid;

alter table "public"."ticket_events" validate constraint "ticket_events_ticket_id_fkey";

alter table "public"."ticket_statuses" add constraint "ticket_statuses_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE not valid;

alter table "public"."ticket_statuses" validate constraint "ticket_statuses_organization_id_fkey";

alter table "public"."tickets" add constraint "tickets_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."tickets" validate constraint "tickets_created_by_fkey";

alter table "public"."tickets" add constraint "tickets_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE not valid;

alter table "public"."tickets" validate constraint "tickets_organization_id_fkey";

alter table "public"."tickets" add constraint "tickets_status_org_fk" FOREIGN KEY (organization_id, status) REFERENCES public.ticket_statuses(organization_id, name) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."tickets" validate constraint "tickets_status_org_fk";

alter table "public"."tickets" add constraint "tickets_ticket_sequence_key" UNIQUE using index "tickets_ticket_sequence_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user_organization_setup()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  new_organization_id integer;
begin
  insert into public.organizations (name)
  values (
    coalesce(
      nullif(trim(coalesce(new.raw_user_meta_data ->> 'name', '')), ''),
      nullif(trim(split_part(coalesce(new.email, ''), '@', 1)), ''),
      'Organization ' || left(new.id::text, 8)
    ) || ' Org'
  )
  returning id into new_organization_id;

  insert into public.members (organization_id, user_id, role)
  values (new_organization_id, new.id, 'ADMIN')
  on conflict (organization_id, user_id) do nothing;

  perform public.seed_default_ticket_statuses_for_organization(new_organization_id);

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user_ticket_statuses()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  perform public.seed_default_ticket_statuses_for_account(new.id);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.has_org_role(target_organization_id integer, allowed_roles public.organization_role[])
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.members m
    where m.organization_id = target_organization_id
      and m.user_id = (select auth.uid())
      and m.role = any(allowed_roles)
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_org_member(target_organization_id integer)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select public.has_org_role(
    target_organization_id,
    array['VIEWER', 'AGENT', 'MANAGER', 'ADMIN']::public.organization_role[]
  );
$function$
;

CREATE OR REPLACE FUNCTION public.seed_default_ticket_statuses_for_account(target_account_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.ticket_statuses (account_id, name, status_type, position, is_default)
  values
    (target_account_id, 'draft', 'draft', 0, true),
    (target_account_id, 'review', 'review', 1, true),
    (target_account_id, 'execute', 'execute', 2, true),
    (target_account_id, 'complete', 'complete', 3, true),
    (target_account_id, 'blocked', 'execute', 4, true),
    (target_account_id, 'cancelled', 'complete', 5, true)
  on conflict (account_id, name) do nothing;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.seed_default_ticket_statuses_for_organization(target_organization_id integer)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.ticket_statuses (organization_id, name, status_type, position, is_default)
  values
    (target_organization_id, 'draft', 'draft', 0, true),
    (target_organization_id, 'review', 'review', 1, true),
    (target_organization_id, 'execute', 'execute', 2, true),
    (target_organization_id, 'complete', 'complete', 3, true),
    (target_organization_id, 'blocked', 'execute', 4, true),
    (target_organization_id, 'cancelled', 'complete', 5, true)
  on conflict (organization_id, name) do nothing;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_ticket_organization_from_creator()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.created_by is null then
    new.created_by := (select auth.uid());
  end if;

  if new.organization_id is null then
    select m.organization_id
      into new.organization_id
    from public.members m
    where m.user_id = new.created_by
    order by
      case m.role
        when 'ADMIN' then 1
        when 'MANAGER' then 2
        when 'AGENT' then 3
        else 4
      end,
      m.organization_id
    limit 1;
  end if;

  if new.organization_id is null then
    raise exception 'No organization membership found for user %', new.created_by;
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$function$
;

grant delete on table "public"."agent_sessions" to "anon";

grant insert on table "public"."agent_sessions" to "anon";

grant references on table "public"."agent_sessions" to "anon";

grant select on table "public"."agent_sessions" to "anon";

grant trigger on table "public"."agent_sessions" to "anon";

grant truncate on table "public"."agent_sessions" to "anon";

grant update on table "public"."agent_sessions" to "anon";

grant delete on table "public"."agent_sessions" to "authenticated";

grant insert on table "public"."agent_sessions" to "authenticated";

grant references on table "public"."agent_sessions" to "authenticated";

grant select on table "public"."agent_sessions" to "authenticated";

grant trigger on table "public"."agent_sessions" to "authenticated";

grant truncate on table "public"."agent_sessions" to "authenticated";

grant update on table "public"."agent_sessions" to "authenticated";

grant delete on table "public"."agent_sessions" to "service_role";

grant insert on table "public"."agent_sessions" to "service_role";

grant references on table "public"."agent_sessions" to "service_role";

grant select on table "public"."agent_sessions" to "service_role";

grant trigger on table "public"."agent_sessions" to "service_role";

grant truncate on table "public"."agent_sessions" to "service_role";

grant update on table "public"."agent_sessions" to "service_role";

grant delete on table "public"."artifacts" to "anon";

grant insert on table "public"."artifacts" to "anon";

grant references on table "public"."artifacts" to "anon";

grant select on table "public"."artifacts" to "anon";

grant trigger on table "public"."artifacts" to "anon";

grant truncate on table "public"."artifacts" to "anon";

grant update on table "public"."artifacts" to "anon";

grant delete on table "public"."artifacts" to "authenticated";

grant insert on table "public"."artifacts" to "authenticated";

grant references on table "public"."artifacts" to "authenticated";

grant select on table "public"."artifacts" to "authenticated";

grant trigger on table "public"."artifacts" to "authenticated";

grant truncate on table "public"."artifacts" to "authenticated";

grant update on table "public"."artifacts" to "authenticated";

grant delete on table "public"."artifacts" to "service_role";

grant insert on table "public"."artifacts" to "service_role";

grant references on table "public"."artifacts" to "service_role";

grant select on table "public"."artifacts" to "service_role";

grant trigger on table "public"."artifacts" to "service_role";

grant truncate on table "public"."artifacts" to "service_role";

grant update on table "public"."artifacts" to "service_role";

grant delete on table "public"."connections" to "anon";

grant insert on table "public"."connections" to "anon";

grant references on table "public"."connections" to "anon";

grant select on table "public"."connections" to "anon";

grant trigger on table "public"."connections" to "anon";

grant truncate on table "public"."connections" to "anon";

grant update on table "public"."connections" to "anon";

grant delete on table "public"."connections" to "authenticated";

grant insert on table "public"."connections" to "authenticated";

grant references on table "public"."connections" to "authenticated";

grant select on table "public"."connections" to "authenticated";

grant trigger on table "public"."connections" to "authenticated";

grant truncate on table "public"."connections" to "authenticated";

grant update on table "public"."connections" to "authenticated";

grant delete on table "public"."connections" to "service_role";

grant insert on table "public"."connections" to "service_role";

grant references on table "public"."connections" to "service_role";

grant select on table "public"."connections" to "service_role";

grant trigger on table "public"."connections" to "service_role";

grant truncate on table "public"."connections" to "service_role";

grant update on table "public"."connections" to "service_role";

grant delete on table "public"."members" to "anon";

grant insert on table "public"."members" to "anon";

grant references on table "public"."members" to "anon";

grant select on table "public"."members" to "anon";

grant trigger on table "public"."members" to "anon";

grant truncate on table "public"."members" to "anon";

grant update on table "public"."members" to "anon";

grant delete on table "public"."members" to "authenticated";

grant insert on table "public"."members" to "authenticated";

grant references on table "public"."members" to "authenticated";

grant select on table "public"."members" to "authenticated";

grant trigger on table "public"."members" to "authenticated";

grant truncate on table "public"."members" to "authenticated";

grant update on table "public"."members" to "authenticated";

grant delete on table "public"."members" to "service_role";

grant insert on table "public"."members" to "service_role";

grant references on table "public"."members" to "service_role";

grant select on table "public"."members" to "service_role";

grant trigger on table "public"."members" to "service_role";

grant truncate on table "public"."members" to "service_role";

grant update on table "public"."members" to "service_role";

grant delete on table "public"."organizations" to "anon";

grant insert on table "public"."organizations" to "anon";

grant references on table "public"."organizations" to "anon";

grant select on table "public"."organizations" to "anon";

grant trigger on table "public"."organizations" to "anon";

grant truncate on table "public"."organizations" to "anon";

grant update on table "public"."organizations" to "anon";

grant delete on table "public"."organizations" to "authenticated";

grant insert on table "public"."organizations" to "authenticated";

grant references on table "public"."organizations" to "authenticated";

grant select on table "public"."organizations" to "authenticated";

grant trigger on table "public"."organizations" to "authenticated";

grant truncate on table "public"."organizations" to "authenticated";

grant update on table "public"."organizations" to "authenticated";

grant delete on table "public"."organizations" to "service_role";

grant insert on table "public"."organizations" to "service_role";

grant references on table "public"."organizations" to "service_role";

grant select on table "public"."organizations" to "service_role";

grant trigger on table "public"."organizations" to "service_role";

grant truncate on table "public"."organizations" to "service_role";

grant update on table "public"."organizations" to "service_role";

grant delete on table "public"."shared_state" to "anon";

grant insert on table "public"."shared_state" to "anon";

grant references on table "public"."shared_state" to "anon";

grant select on table "public"."shared_state" to "anon";

grant trigger on table "public"."shared_state" to "anon";

grant truncate on table "public"."shared_state" to "anon";

grant update on table "public"."shared_state" to "anon";

grant delete on table "public"."shared_state" to "authenticated";

grant insert on table "public"."shared_state" to "authenticated";

grant references on table "public"."shared_state" to "authenticated";

grant select on table "public"."shared_state" to "authenticated";

grant trigger on table "public"."shared_state" to "authenticated";

grant truncate on table "public"."shared_state" to "authenticated";

grant update on table "public"."shared_state" to "authenticated";

grant delete on table "public"."shared_state" to "service_role";

grant insert on table "public"."shared_state" to "service_role";

grant references on table "public"."shared_state" to "service_role";

grant select on table "public"."shared_state" to "service_role";

grant trigger on table "public"."shared_state" to "service_role";

grant truncate on table "public"."shared_state" to "service_role";

grant update on table "public"."shared_state" to "service_role";

grant delete on table "public"."ticket_events" to "anon";

grant insert on table "public"."ticket_events" to "anon";

grant references on table "public"."ticket_events" to "anon";

grant select on table "public"."ticket_events" to "anon";

grant trigger on table "public"."ticket_events" to "anon";

grant truncate on table "public"."ticket_events" to "anon";

grant update on table "public"."ticket_events" to "anon";

grant delete on table "public"."ticket_events" to "authenticated";

grant insert on table "public"."ticket_events" to "authenticated";

grant references on table "public"."ticket_events" to "authenticated";

grant select on table "public"."ticket_events" to "authenticated";

grant trigger on table "public"."ticket_events" to "authenticated";

grant truncate on table "public"."ticket_events" to "authenticated";

grant update on table "public"."ticket_events" to "authenticated";

grant delete on table "public"."ticket_events" to "service_role";

grant insert on table "public"."ticket_events" to "service_role";

grant references on table "public"."ticket_events" to "service_role";

grant select on table "public"."ticket_events" to "service_role";

grant trigger on table "public"."ticket_events" to "service_role";

grant truncate on table "public"."ticket_events" to "service_role";

grant update on table "public"."ticket_events" to "service_role";

grant delete on table "public"."ticket_statuses" to "anon";

grant insert on table "public"."ticket_statuses" to "anon";

grant references on table "public"."ticket_statuses" to "anon";

grant select on table "public"."ticket_statuses" to "anon";

grant trigger on table "public"."ticket_statuses" to "anon";

grant truncate on table "public"."ticket_statuses" to "anon";

grant update on table "public"."ticket_statuses" to "anon";

grant delete on table "public"."ticket_statuses" to "authenticated";

grant insert on table "public"."ticket_statuses" to "authenticated";

grant references on table "public"."ticket_statuses" to "authenticated";

grant select on table "public"."ticket_statuses" to "authenticated";

grant trigger on table "public"."ticket_statuses" to "authenticated";

grant truncate on table "public"."ticket_statuses" to "authenticated";

grant update on table "public"."ticket_statuses" to "authenticated";

grant delete on table "public"."ticket_statuses" to "service_role";

grant insert on table "public"."ticket_statuses" to "service_role";

grant references on table "public"."ticket_statuses" to "service_role";

grant select on table "public"."ticket_statuses" to "service_role";

grant trigger on table "public"."ticket_statuses" to "service_role";

grant truncate on table "public"."ticket_statuses" to "service_role";

grant update on table "public"."ticket_statuses" to "service_role";

grant delete on table "public"."tickets" to "anon";

grant insert on table "public"."tickets" to "anon";

grant references on table "public"."tickets" to "anon";

grant select on table "public"."tickets" to "anon";

grant trigger on table "public"."tickets" to "anon";

grant truncate on table "public"."tickets" to "anon";

grant update on table "public"."tickets" to "anon";

grant delete on table "public"."tickets" to "authenticated";

grant insert on table "public"."tickets" to "authenticated";

grant references on table "public"."tickets" to "authenticated";

grant select on table "public"."tickets" to "authenticated";

grant trigger on table "public"."tickets" to "authenticated";

grant truncate on table "public"."tickets" to "authenticated";

grant update on table "public"."tickets" to "authenticated";

grant delete on table "public"."tickets" to "service_role";

grant insert on table "public"."tickets" to "service_role";

grant references on table "public"."tickets" to "service_role";

grant select on table "public"."tickets" to "service_role";

grant trigger on table "public"."tickets" to "service_role";

grant truncate on table "public"."tickets" to "service_role";

grant update on table "public"."tickets" to "service_role";


  create policy "agent_sessions_delete_local"
  on "public"."agent_sessions"
  as permissive
  for delete
  to anon, authenticated
using (true);



  create policy "agent_sessions_insert_local"
  on "public"."agent_sessions"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "agent_sessions_select_local"
  on "public"."agent_sessions"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "agent_sessions_update_local"
  on "public"."agent_sessions"
  as permissive
  for update
  to anon, authenticated
using (true)
with check (true);



  create policy "artifacts_delete_local"
  on "public"."artifacts"
  as permissive
  for delete
  to anon, authenticated
using (true);



  create policy "artifacts_insert_local"
  on "public"."artifacts"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "artifacts_select_local"
  on "public"."artifacts"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "artifacts_update_local"
  on "public"."artifacts"
  as permissive
  for update
  to anon, authenticated
using (true)
with check (true);



  create policy "connections_delete_local"
  on "public"."connections"
  as permissive
  for delete
  to anon, authenticated
using (true);



  create policy "connections_insert_local"
  on "public"."connections"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "connections_select_local"
  on "public"."connections"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "connections_update_local"
  on "public"."connections"
  as permissive
  for update
  to anon, authenticated
using (true)
with check (true);



  create policy "members_delete_admin"
  on "public"."members"
  as permissive
  for delete
  to authenticated
using (public.has_org_role(organization_id, ARRAY['ADMIN'::public.organization_role]));



  create policy "members_insert_admin"
  on "public"."members"
  as permissive
  for insert
  to authenticated
with check (public.has_org_role(organization_id, ARRAY['ADMIN'::public.organization_role]));



  create policy "members_select_member"
  on "public"."members"
  as permissive
  for select
  to authenticated
using (public.is_org_member(organization_id));



  create policy "members_update_admin"
  on "public"."members"
  as permissive
  for update
  to authenticated
using (public.has_org_role(organization_id, ARRAY['ADMIN'::public.organization_role]))
with check (public.has_org_role(organization_id, ARRAY['ADMIN'::public.organization_role]));



  create policy "organizations_delete_admin"
  on "public"."organizations"
  as permissive
  for delete
  to authenticated
using (public.has_org_role(id, ARRAY['ADMIN'::public.organization_role]));



  create policy "organizations_insert_authenticated"
  on "public"."organizations"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "organizations_select_member"
  on "public"."organizations"
  as permissive
  for select
  to authenticated
using (public.is_org_member(id));



  create policy "organizations_update_admin"
  on "public"."organizations"
  as permissive
  for update
  to authenticated
using (public.has_org_role(id, ARRAY['ADMIN'::public.organization_role]))
with check (public.has_org_role(id, ARRAY['ADMIN'::public.organization_role]));



  create policy "shared_state_delete_local"
  on "public"."shared_state"
  as permissive
  for delete
  to anon, authenticated
using (true);



  create policy "shared_state_insert_local"
  on "public"."shared_state"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "shared_state_select_local"
  on "public"."shared_state"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "shared_state_update_local"
  on "public"."shared_state"
  as permissive
  for update
  to anon, authenticated
using (true)
with check (true);



  create policy "ticket_events_delete_local"
  on "public"."ticket_events"
  as permissive
  for delete
  to anon, authenticated
using (true);



  create policy "ticket_events_insert_local"
  on "public"."ticket_events"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "ticket_events_select_local"
  on "public"."ticket_events"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "ticket_events_update_local"
  on "public"."ticket_events"
  as permissive
  for update
  to anon, authenticated
using (true)
with check (true);



  create policy "ticket_statuses_delete_admin"
  on "public"."ticket_statuses"
  as permissive
  for delete
  to authenticated
using (public.has_org_role(organization_id, ARRAY['ADMIN'::public.organization_role]));



  create policy "ticket_statuses_insert_admin"
  on "public"."ticket_statuses"
  as permissive
  for insert
  to authenticated
with check (public.has_org_role(organization_id, ARRAY['ADMIN'::public.organization_role]));



  create policy "ticket_statuses_select_member"
  on "public"."ticket_statuses"
  as permissive
  for select
  to authenticated
using (public.is_org_member(organization_id));



  create policy "ticket_statuses_update_admin"
  on "public"."ticket_statuses"
  as permissive
  for update
  to authenticated
using (public.has_org_role(organization_id, ARRAY['ADMIN'::public.organization_role]))
with check (public.has_org_role(organization_id, ARRAY['ADMIN'::public.organization_role]));



  create policy "tickets_delete_manager_plus"
  on "public"."tickets"
  as permissive
  for delete
  to authenticated
using (public.has_org_role(organization_id, ARRAY['MANAGER'::public.organization_role, 'ADMIN'::public.organization_role]));



  create policy "tickets_insert_agent_plus"
  on "public"."tickets"
  as permissive
  for insert
  to authenticated
with check ((public.has_org_role(organization_id, ARRAY['AGENT'::public.organization_role, 'MANAGER'::public.organization_role, 'ADMIN'::public.organization_role]) AND (created_by = ( SELECT auth.uid() AS uid))));



  create policy "tickets_select_member"
  on "public"."tickets"
  as permissive
  for select
  to authenticated
using (public.is_org_member(organization_id));



  create policy "tickets_update_agent_plus"
  on "public"."tickets"
  as permissive
  for update
  to authenticated
using (public.has_org_role(organization_id, ARRAY['AGENT'::public.organization_role, 'MANAGER'::public.organization_role, 'ADMIN'::public.organization_role]))
with check (public.has_org_role(organization_id, ARRAY['AGENT'::public.organization_role, 'MANAGER'::public.organization_role, 'ADMIN'::public.organization_role]));


CREATE TRIGGER set_agent_sessions_updated_at BEFORE UPDATE ON public.agent_sessions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_connections_updated_at BEFORE UPDATE ON public.connections FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_members_updated_at BEFORE UPDATE ON public.members FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_organizations_updated_at BEFORE UPDATE ON public.organizations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_ticket_statuses_updated_at BEFORE UPDATE ON public.ticket_statuses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_tickets_organization_before_insert BEFORE INSERT ON public.tickets FOR EACH ROW EXECUTE FUNCTION public.set_ticket_organization_from_creator();

CREATE TRIGGER set_tickets_updated_at BEFORE UPDATE ON public.tickets FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER on_auth_user_created_organization_setup AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user_organization_setup();


