/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: string;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: string;
  userId: string;
}

export interface AccountConnectionAuthorizations {
  connection_id: string;
  consumed_at: string | null;
  created_at: string;
  expires_at: string;
  id: string | null;
  pkce_verifier_ciphertext: string;
  return_to: string;
  return_url: string | null;
  state_hash: string;
}

export interface AccountConnections {
  access_expires_at: string | null;
  assistant_write_scope: Generated<string>;
  authorized_workspaces_json: Generated<string>;
  connected_at: string | null;
  created_at: string;
  credential_ciphertext: string | null;
  credential_format: Generated<string>;
  credential_key_id: string | null;
  credential_kind: Generated<string>;
  credential_revision: Generated<number>;
  disconnected_at: string | null;
  external_account_avatar_url: string | null;
  external_account_id: string | null;
  external_account_label: string | null;
  granted_scopes_json: Generated<string>;
  id: string | null;
  last_error_code: string | null;
  last_refreshed_at: string | null;
  last_validated_at: string | null;
  organization_id: string | null;
  owner_profile_id: string;
  provider: string;
  refresh_expires_at: string | null;
  refresh_lock_owner: string | null;
  refresh_lock_until: string | null;
  revision: Generated<number>;
  server_url: string;
  state: string;
  tool_policy_version: Generated<number>;
  updated_at: string;
}

export interface AgentRequests {
  allows_free_text: Generated<number>;
  application_observed_at: string | null;
  application_state: Generated<string>;
  channel_id: string;
  created_at: string;
  deleted_at: string | null;
  details_json: Generated<string>;
  expires_at: string | null;
  first_viewed_at: string | null;
  formatter_version: Generated<number>;
  id: string | null;
  kind: string;
  mission_id: string | null;
  native_call_id: string | null;
  native_request_id: string | null;
  objective_id: string | null;
  options_json: Generated<string>;
  project_id: string | null;
  released_reason: string | null;
  resolution_json: string | null;
  resolved_at: string | null;
  resolved_by_workspace_user_id: string | null;
  revision: Generated<number>;
  session_id: string | null;
  source_event_id: string | null;
  status: Generated<string>;
  summary: string;
  updated_at: string;
  waiter_lease_expires_at: string | null;
  waiter_lease_id: string | null;
  window_basis: string | null;
  window_expires_at: string | null;
  workspace_id: string;
}

export interface AgentSessionChannels {
  adapter_key: string | null;
  adapter_version: string | null;
  agent_identifier: string | null;
  capabilities_json: Generated<string>;
  created_at: string;
  created_by_workspace_user_id: string | null;
  credential_algorithm: Generated<string>;
  credential_expires_at: string | null;
  credential_hash: string | null;
  credential_prefix: string | null;
  credential_revoked_at: string | null;
  deleted_at: string | null;
  end_reason: string | null;
  ended_at: string | null;
  execution_request_id: string | null;
  execution_target_id: string | null;
  exit_code: number | null;
  id: string | null;
  last_heartbeat_at: string | null;
  launch_kind: Generated<string>;
  launch_prompt_id: string | null;
  lease_expires_at: string | null;
  mission_id: string | null;
  native_session_id: string | null;
  objective_id: string | null;
  project_id: string | null;
  revision: Generated<number>;
  runner_registration_id: string | null;
  session_id: string | null;
  state: Generated<string>;
  updated_at: string;
  workspace_id: string;
}

export interface AgentSessionEvents {
  actionability: string | null;
  adapter_key: string;
  channel_id: string;
  channel_sequence: number;
  correlation_id: string | null;
  created_at: string;
  deleted_at: string | null;
  formatter_version: Generated<number>;
  id: string | null;
  kind: string;
  mission_event_id: string | null;
  mission_id: string | null;
  native_call_id: string | null;
  native_event: string | null;
  native_turn_id: string | null;
  objective_id: string | null;
  occurred_at: string;
  origin: string | null;
  payload_json: Generated<string>;
  producer_event_id: string;
  producer_sequence: number | null;
  project_id: string | null;
  received_at: string;
  revision: Generated<number>;
  session_id: string | null;
  severity: Generated<string>;
  subagent_id: string | null;
  summary: string | null;
  updated_at: string;
  workspace_id: string;
}

export interface AgentSessionInputs {
  acknowledged_at: string | null;
  attempt_count: Generated<number>;
  body: string;
  channel_id: string;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  delivery_outcome: string | null;
  emitted_at: string | null;
  id: string | null;
  idempotency_key: string | null;
  kind: string;
  last_error_code: string | null;
  lease_expires_at: string | null;
  lease_id: string | null;
  mission_id: string | null;
  objective_id: string | null;
  project_id: string | null;
  revision: Generated<number>;
  session_id: string;
  status: Generated<string>;
  updated_at: string;
  workspace_id: string;
}

export interface AgentSessions {
  agent_identifier: string;
  connection_method: string;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  delivery_state: string;
  ended_at: string | null;
  external_session_id: string | null;
  id: string | null;
  last_heartbeat_at: string | null;
  metadata_json: Generated<string>;
  mission_id: string;
  model_identifier: string | null;
  objective_id: string;
  phase: string;
  project_id: string;
  revision: Generated<number>;
  session_key_hash: string;
  session_key_prefix: string;
  started_at: string;
  updated_at: string;
  workspace_id: string;
}

export interface Artifacts {
  content_json: string | null;
  content_text: string | null;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  delivery_id: string | null;
  external_url: string | null;
  id: string | null;
  label: string;
  mission_id: string;
  objective_id: string | null;
  project_id: string;
  revision: Generated<number>;
  session_id: string | null;
  type: string;
  updated_at: string;
  workspace_id: string;
}

export interface Attachments {
  checksum_sha256: string | null;
  content_type: string | null;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  filename: string;
  id: string | null;
  metadata_json: Generated<string>;
  mission_id: string | null;
  objective_id: string | null;
  project_id: string | null;
  revision: Generated<number>;
  size_bytes: number | null;
  storage_bucket_id: string;
  storage_key: string;
  updated_at: string;
  upload_status: string;
  workspace_id: string;
}

export interface ChangedFiles {
  created_at: string;
  current_diff_state: string;
  deleted_at: string | null;
  file_path: string;
  first_observed_at: string;
  id: string | null;
  last_observed_at: string;
  last_observed_event_id: string | null;
  mission_id: string;
  objective_id: string;
  observed_metadata_json: Generated<string>;
  project_id: string;
  resource_id: string | null;
  revision: Generated<number>;
  session_id: string | null;
  updated_at: string;
  vcs_status: string | null;
  workspace_id: string;
}

export interface ChangeRationales {
  changed_file_id: string | null;
  created_at: string;
  deleted_at: string | null;
  delivery_id: string | null;
  file_path: string;
  hunks_json: Generated<string>;
  id: string | null;
  impact: string;
  is_final: Generated<number>;
  label: string;
  mission_id: string;
  objective_id: string;
  project_id: string;
  revision: Generated<number>;
  session_id: string | null;
  source_event_id: string | null;
  summary: string;
  updated_at: string;
  why: string;
  workspace_id: string;
}

export interface ChatDependencySetMembers {
  dependency_set_id: string;
  source_ref_id: string;
}

export interface ChatDependencySets {
  created_at: string;
  digest: string;
  id: string | null;
  invalidated_at: string | null;
  thread_id: string;
}

export interface ChatDiagnostics {
  attempt_id: string | null;
  created_at: string;
  kind: string;
  payload_json: string;
  run_id: string | null;
  seq: number;
  thread_id: string;
}

export interface ChatEventAcks {
  acked_at: string;
  acked_seq: number;
  client_id: string;
  created_at: string;
  thread_id: string;
}

export interface ChatEvents {
  attempt_id: string | null;
  created_at: string;
  dependency_set_id: string | null;
  fence: number | null;
  id: string | null;
  kind: string;
  payload_json: string;
  run_id: string | null;
  seq: number;
  thread_id: string;
}

export interface ChatEvidence {
  created_at: string;
  excerpt: string | null;
  excerpt_truncated: Generated<number>;
  id: string | null;
  label: string;
  observed_at: string;
  run_id: string | null;
  source_ref_id: string;
  source_revision: string | null;
  thread_id: string;
  tool_call_id: string | null;
}

export interface ChatMessages {
  answers_question_id: string | null;
  blocks_json: Generated<string>;
  client_request_id: string | null;
  created_at: string;
  dependency_set_id: string | null;
  id: string | null;
  invalidated_at: string | null;
  revision: Generated<number>;
  role: string;
  run_id: string | null;
  state: string;
  thread_id: string;
  updated_at: string;
}

export interface ChatNotifications {
  attempt_count: Generated<number>;
  created_at: string;
  deleted_at: string | null;
  dispatched_at: string | null;
  due_at: string;
  event_seq: number;
  id: string | null;
  last_error: string | null;
  locked_by: string | null;
  locked_until: string | null;
  max_attempts: Generated<number>;
  organization_id: string;
  owner_profile_id: string;
  question_id: string | null;
  read_at: string | null;
  revision: Generated<number>;
  run_id: string;
  state: string;
  suppressed_at: string | null;
  suppressed_by_client_id: string | null;
  thread_id: string;
  thread_title: string | null;
  transition_key: string;
  type: string;
  updated_at: string;
}

export interface ChatPresence {
  client_id: string;
  created_at: string;
  expires_at: string;
  platform: string;
  released_at: string | null;
  thread_id: string;
  updated_at: string;
}

export interface ChatProviderCheckpoints {
  attempt_id: string;
  config_digest: string;
  created_at: string;
  dependency_set_id: string | null;
  fence: number;
  invalidated_at: string | null;
  model: string;
  payload_json: string;
  phase: string;
  provider: string;
  revision: Generated<number>;
  run_id: string | null;
  schema_version: number;
  updated_at: string;
}

export interface ChatQuestions {
  allow_free_text: Generated<number>;
  answer_message_id: string | null;
  answered_at: string | null;
  created_at: string;
  dependency_set_id: string | null;
  id: string | null;
  options_json: Generated<string>;
  ordinal: number;
  prompt: string;
  revision: Generated<number>;
  run_id: string;
  state: string;
  thread_id: string;
  updated_at: string;
}

export interface ChatRunAttempts {
  attempt_number: number;
  config_digest: string | null;
  ended_at: string | null;
  failure_code: string | null;
  fence: number;
  id: string | null;
  lease_expires_at: string | null;
  lease_owner: string | null;
  model: string;
  provider: string;
  recovery_mode: string;
  run_id: string;
  started_at: string;
  state: string;
}

export interface ChatRuns {
  active_attempt_id: string | null;
  active_processing_ms: Generated<number>;
  cancel_requested_at: string | null;
  completed_at: string | null;
  continued_from_run_id: string | null;
  created_at: string;
  current_fence: Generated<number>;
  failure_code: string | null;
  gathered_content_bytes: Generated<number>;
  id: string | null;
  knowledgebase_write_json: string | null;
  limits_json: Generated<string>;
  outcome: string | null;
  revision: Generated<number>;
  state: string;
  thread_id: string;
  tool_call_count: Generated<number>;
  trigger_message_id: string | null;
  updated_at: string;
}

export interface ChatSourceRefs {
  access_checked_at: string;
  access_state: string;
  connection_id: string | null;
  created_at: string;
  execution_target_id: string | null;
  id: string | null;
  locator_json: string;
  project_id: string | null;
  resource_key: string | null;
  revision: Generated<number>;
  scope_key: string;
  source_kind: string;
  source_revision: string | null;
  thread_id: string;
  updated_at: string;
  workspace_id: string | null;
}

export interface ChatThreads {
  archived_at: string | null;
  authorization_revision: Generated<number>;
  created_at: string;
  id: string | null;
  last_activity_at: string;
  last_event_seq: Generated<number>;
  organization_id: string;
  owner_profile_id: string;
  retained_from_seq: Generated<number>;
  revision: Generated<number>;
  title: Generated<string>;
  title_source: Generated<string>;
  updated_at: string;
}

export interface ChatThreadSummaries {
  covers_through_message_id: string | null;
  created_at: string;
  dependency_set_id: string | null;
  id: string | null;
  invalidated_at: string | null;
  summary_json: string;
  summary_revision: number;
  thread_id: string;
}

export interface ChatToolCalls {
  arguments_json: Generated<string>;
  attempt_id: string;
  call_order: number;
  completed_at: string | null;
  created_at: string;
  dependency_set_id: string | null;
  error_code: string | null;
  executions: Generated<number>;
  id: string | null;
  operation_id: string;
  policy_version: number;
  provider_call_id: string | null;
  requested_fence: number;
  result_bytes: number | null;
  result_json: string | null;
  result_truncated: Generated<number>;
  run_id: string;
  state: string;
  tool_id: string;
  turn_index: number;
  updated_at: string;
  writer_fence: number;
}

export interface ChatWorkProposalRevisions {
  created_at: string;
  dependency_set_id: string | null;
  invalidated_at: string | null;
  proposal_id: string;
  proposal_revision: number;
  responsible_profile_id: string;
  run_id: string | null;
  spec_json: string;
}

export interface ChatWorkProposals {
  created_at: string;
  created_by_run_id: string | null;
  current_revision: number;
  id: string | null;
  revision: Generated<number>;
  state: string;
  thread_id: string;
  updated_at: string;
}

export interface ChatWorkReceiptMissions {
  mission_id: string;
  objective_ids_json: Generated<string>;
  position: number;
  project_id: string;
  receipt_id: string;
  workspace_id: string;
}

export interface ChatWorkReceipts {
  authorization_revision: number;
  client_request_id: string;
  created_at: string;
  id: string | null;
  owner_profile_id: string;
  proposal_id: string;
  proposal_revision: number;
  request_digest: string;
}

export interface Deliveries {
  created_at: string;
  deleted_at: string | null;
  delivered_at: string;
  delivered_by_workspace_user_id: string | null;
  follow_up_notes: string | null;
  id: string | null;
  mission_id: string;
  objective_id: string;
  payload_json: Generated<string>;
  project_id: string;
  revision: Generated<number>;
  session_id: string | null;
  summary: string;
  updated_at: string;
  verification_summary: string | null;
  workspace_id: string;
}

export interface DevicePushTokens {
  app_version: string | null;
  bundle_id: string;
  created_at: string;
  device_token: string;
  environment: string;
  id: string | null;
  last_registered_at: string;
  last_sent_at: string | null;
  platform: string;
  profile_id: string;
  updated_at: string;
}

export interface Devices {
  created_at: string;
  deleted_at: string | null;
  fingerprint: string;
  id: string | null;
  label: string;
  last_seen_at: string | null;
  metadata_json: Generated<string>;
  platform: string | null;
  revision: Generated<number>;
  status: string;
  updated_at: string;
  workspace_id: string;
}

export interface EntityChanges {
  actor_token_id: string | null;
  actor_workspace_user_id: string | null;
  changed_fields_json: Generated<string>;
  entity_id: string;
  entity_revision: number | null;
  entity_type: string;
  id: string;
  mission_id: string | null;
  objective_id: string | null;
  occurred_at: string;
  operation: string;
  project_id: string | null;
  seq: Generated<number | null>;
  source: string;
  workspace_id: string;
}

export interface ExecutionRequestGrants {
  consumed_at: string | null;
  created_at: string;
  execution_request_id: string;
  expires_at: string;
  grant_hash: string;
  id: string | null;
  kind: string;
  revoked_at: string | null;
  scope_json: Generated<string>;
  updated_at: string;
  workspace_id: string;
}

export interface ExecutionRequestObservations {
  created_at: string;
  execution_request_id: string;
  id: string | null;
  kind: string;
  observation_json: Generated<string>;
  observed_at: string;
  sequence: number;
  workspace_id: string;
}

export interface ExecutionRequests {
  attempt_count: Generated<number>;
  claim_expires_at: string | null;
  claimed_at: string | null;
  claimed_by_device_id: string | null;
  claimed_by_execution_target_id: string | null;
  claimed_by_gateway_instance_id: string | null;
  claimed_by_runner_registration_id: string | null;
  created_at: string;
  deleted_at: string | null;
  execution_target_id: string | null;
  failure_code: string | null;
  failure_phase: string | null;
  id: string | null;
  idempotency_key: string | null;
  last_error: string | null;
  launch_completed_at: string | null;
  launch_flags_json: Generated<string>;
  launch_mode: string;
  launch_snapshot_id: string | null;
  launch_started_at: string | null;
  launched_session_id: string | null;
  metadata_json: Generated<string>;
  mission_id: string | null;
  objective_id: string | null;
  project_id: string;
  requested_agent: string | null;
  requested_by_workspace_user_id: string | null;
  requested_model: string | null;
  requested_reasoning_effort: string | null;
  requested_source: string;
  resolved_resource_id: string | null;
  resolved_working_directory: string | null;
  revision: Generated<number>;
  status: string;
  updated_at: string;
  workspace_id: string;
}

export interface ExecutionRequestSnapshots {
  created_at: string;
  execution_request_id: string;
  id: string | null;
  payload_digest: string;
  payload_json: Generated<string>;
  schema_version: string;
  workspace_id: string;
}

export interface ExecutionTargetRegistrations {
  capabilities_json: Generated<string>;
  connection_json: Generated<string>;
  created_at: string;
  deleted_at: string | null;
  execution_target_id: string;
  gateway_instance_id: string;
  gateway_key: string;
  gateway_version: string | null;
  health: string;
  id: string | null;
  last_error_code: string | null;
  last_heartbeat_at: string | null;
  revision: Generated<number>;
  supported_agents_json: Generated<string>;
  supported_queue_versions_json: Generated<string>;
  updated_at: string;
  workspace_id: string;
}

export interface ExecutionTargetRunnerRegistrations {
  capabilities_json: Generated<string>;
  created_at: string;
  deleted_at: string | null;
  execution_target_id: string;
  health: string;
  id: string | null;
  label: string | null;
  last_error_code: string | null;
  last_heartbeat_at: string | null;
  relation: string;
  revision: Generated<number>;
  runner_instance_id: string;
  runner_version: string | null;
  supported_agents_json: Generated<string>;
  updated_at: string;
  workspace_id: string;
}

export interface ExecutionTargets {
  connection_json: Generated<string>;
  created_at: string;
  deleted_at: string | null;
  device_id: string | null;
  id: string | null;
  label: string;
  owner_workspace_user_id: string | null;
  revision: Generated<number>;
  status: string;
  type: string;
  updated_at: string;
  workspace_id: string;
}

export interface ExtEverhourMissionLinks {
  created_at: string;
  deleted_at: string | null;
  everhour_task_id: string;
  id: string | null;
  mission_id: string;
  project_id: string;
  revision: Generated<number>;
  updated_at: string;
  workspace_id: string;
}

export interface ExtEverhourProjectLinks {
  created_at: string;
  deleted_at: string | null;
  everhour_general_task_id: string | null;
  everhour_project_id: string;
  everhour_project_name: string;
  everhour_section_id: string | null;
  id: string | null;
  project_id: string;
  revision: Generated<number>;
  updated_at: string;
  workspace_id: string;
}

export interface ExtEverhourUserConnections {
  account_id: string | null;
  account_name: string | null;
  api_key_ciphertext: string;
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  last_validated_at: string;
  profile_id: string;
  revision: Generated<number>;
  updated_at: string;
}

export interface ExtEverhourWorkspaceConnections {
  account_id: string | null;
  account_name: string | null;
  api_key_secret: string;
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  revision: Generated<number>;
  updated_at: string;
  workspace_id: string;
}

export interface ExtGithubInstallations {
  created_at: string;
  deleted_at: string | null;
  github_account_login: string;
  github_account_type: string | null;
  github_installation_id: string;
  id: string | null;
  permissions_json: Generated<string>;
  revision: Generated<number>;
  updated_at: string;
  workspace_id: string;
}

export interface ExtGithubMissionPullRequests {
  base_branch: string;
  created_at: string;
  deleted_at: string | null;
  github_pull_number: number;
  head_branch: string;
  html_url: string;
  id: string | null;
  mission_id: string;
  project_id: string;
  revision: Generated<number>;
  state: string;
  updated_at: string;
  workspace_id: string;
}

export interface ExtGithubProjectInitializations {
  clone_url: string | null;
  created_at: string;
  default_branch: string | null;
  deleted_at: string | null;
  failure_message: string | null;
  full_name: string | null;
  github_owner_login: string | null;
  github_repo_id: string | null;
  id: string | null;
  idempotency_key: string;
  mission_id: string;
  profile_id: string;
  project_id: string;
  provisioning_status: string;
  revision: Generated<number>;
  updated_at: string;
  workspace_id: string;
}

export interface ExtGithubProjectLinks {
  created_at: string;
  default_branch: string;
  deleted_at: string | null;
  full_name: string;
  github_repo_id: string;
  id: string | null;
  metadata_json: Generated<string>;
  project_id: string;
  revision: Generated<number>;
  updated_at: string;
  workspace_id: string;
}

export interface ExtGithubUserConnections {
  access_token_ciphertext: string;
  access_token_expires_at: string | null;
  avatar_url: string | null;
  created_at: string;
  deleted_at: string | null;
  github_login: string;
  github_user_id: string;
  id: string | null;
  last_validated_at: string;
  profile_id: string;
  refresh_token_ciphertext: string | null;
  refresh_token_expires_at: string | null;
  revision: Generated<number>;
  scopes_json: Generated<string>;
  updated_at: string;
}

export interface ExtGithubUserOauthStates {
  consumed_at: string | null;
  created_at: string;
  deleted_at: string | null;
  expires_at: string;
  id: string | null;
  profile_id: string;
  return_url: string | null;
  revision: Generated<number>;
  state_hash: string;
  updated_at: string;
}

export interface HumanActionResolutions {
  action_id: string;
  delivery_id: string;
  mission_id: string;
  objective_id: string;
  outcome: string | null;
  outcome_ref: string | null;
  resolved_at: string;
  resolved_by_workspace_user_id: string | null;
  status: string;
  workspace_id: string;
}

export interface IdempotencyKeys {
  actor_workspace_user_id: string | null;
  created_at: string;
  expires_at: string;
  id: string | null;
  key: string;
  request_hash: string;
  response_json: string | null;
  scope: string;
  status: string;
  updated_at: string;
  workspace_id: string;
}

export interface InboxItems {
  created_at: string;
  due_datetime: string | null;
  id: string | null;
  objectives_json: string;
  priority: string | null;
  profile_id: string;
  title: string;
  updated_at: string;
}

export interface LiveActivityPushTokens {
  activity_id: string;
  bundle_id: string;
  created_at: string;
  environment: string;
  id: string | null;
  last_content_hash: string | null;
  last_sent_at: string | null;
  origin: Generated<string>;
  profile_id: string;
  push_token: string;
  updated_at: string;
}

export interface LiveActivityStartTokens {
  activity_type: string;
  app_version: string | null;
  bundle_id: string;
  created_at: string;
  environment: string;
  id: string | null;
  last_registered_at: string;
  last_started_at: string | null;
  platform: string;
  profile_id: string;
  start_token: string;
  updated_at: string;
}

export interface MissionBranchObservations {
  created_at: string;
  dirty: number;
  execution_target_id: string;
  id: string | null;
  mission_id: string;
  observed_at: string;
  resource_key: Generated<string>;
  status: string;
  updated_at: string;
  workspace_id: string;
  worktree_path: string | null;
}

export interface MissionEvents {
  actor_token_id: string | null;
  actor_workspace_user_id: string | null;
  created_at: string;
  external_url: string | null;
  id: string | null;
  idempotency_key: string | null;
  mission_id: string;
  objective_id: string | null;
  payload_json: Generated<string>;
  phase: string | null;
  project_id: string;
  session_id: string | null;
  source: string;
  summary: string;
  type: string;
  workspace_id: string;
}

export interface Missions {
  active_branch: string | null;
  allow_parallel_objectives: Generated<number>;
  assigned_workspace_user_id: string | null;
  blocking_question_seen_at: string | null;
  board_position: Generated<number>;
  branch_override: string | null;
  constraints_text: string | null;
  created_at: string;
  created_by_agent: string | null;
  created_by_kind: Generated<string>;
  created_by_session_id: string | null;
  created_by_token_id: string | null;
  created_by_token_label: string | null;
  created_by_workspace_user_id: string | null;
  created_from_chat_thread_id: string | null;
  deleted_at: string | null;
  display_id: string;
  due_datetime: string | null;
  execution_target_intent_json: Generated<string>;
  id: string | null;
  metadata_json: Generated<string>;
  notes_text: string | null;
  output_format_text: string | null;
  priority: string | null;
  project_id: string;
  returned_to_execute_at: string | null;
  revision: Generated<number>;
  schedule_id: string | null;
  sequence_number: number;
  status_id: string;
  status_type: string;
  title: string;
  updated_at: string;
  workspace_id: string;
  worktree_preference: string | null;
}

export interface MissionSequences {
  counter_name: string;
  id: string | null;
  next_value: number;
  scope_id: string;
  scope_type: string;
  updated_at: string;
  workspace_id: string;
}

export interface MissionStatusSeen {
  mission_id: string;
  seen_at: string;
  status_id: string;
}

export interface MissionTags {
  created_at: string;
  mission_id: string;
  tag_id: string;
}

export interface MissionTargetResources {
  created_at: string;
  deleted_at: string | null;
  execution_target_id: string;
  external_id: string;
  id: string | null;
  kind: string;
  latest_observation_json: Generated<string>;
  mission_id: string;
  revision: Generated<number>;
  state: string;
  updated_at: string;
  workspace_id: string;
}

export interface MyMissionPositions {
  created_at: string;
  id: string | null;
  mission_id: string;
  position: number;
  project_id: string;
  revision: Generated<number>;
  status_id: string;
  updated_at: string;
  workspace_id: string;
  workspace_user_id: string;
}

export interface NotificationPreferences {
  created_at: string;
  id: string | null;
  mode: string;
  profile_id: string;
  transport: string;
  type: string;
  updated_at: string;
}

export interface Notifications {
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  mission_id: string;
  objective_id: string | null;
  read_at: string | null;
  recipient_profile_id: string;
  revision: Generated<number>;
  type: string;
  workspace_id: string;
}

export interface ObjectiveAttachments {
  checksum_sha256: string | null;
  content_type: string | null;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  filename: string;
  id: string | null;
  metadata_json: Generated<string>;
  mission_id: string;
  objective_id: string;
  revision: Generated<number>;
  size_bytes: number | null;
  storage_backend: string;
  storage_key: string;
  updated_at: string;
  upload_status: string;
  workspace_id: string;
}

export interface Objectives {
  agent_flags_json: Generated<string>;
  approval_reason: string | null;
  assigned_agent: string | null;
  auto_advance: Generated<number>;
  auto_advanced_at: string | null;
  branch: string | null;
  completed_at: string | null;
  created_at: string;
  created_by_agent: string | null;
  created_by_kind: Generated<string>;
  created_by_session_id: string | null;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  display_key: Generated<string>;
  execution_metadata_json: Generated<string>;
  id: string | null;
  instruction_text: string | null;
  launch_config_json: string | null;
  launched_at: string | null;
  mission_id: string;
  model: string | null;
  position: number;
  project_id: string;
  reasoning_effort: string | null;
  reopened_at: string | null;
  resource_key: string | null;
  revision: Generated<number>;
  started_at: string | null;
  state: string;
  title: string | null;
  updated_at: string;
  workspace_id: string;
}

export interface Organizations {
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  name: string;
  revision: Generated<number>;
  settings_json: Generated<string>;
  updated_at: string;
}

export interface OutboxMessages {
  attempt_count: Generated<number>;
  available_at: string;
  created_at: string;
  id: string | null;
  last_error: string | null;
  payload_json: string;
  status: Generated<string>;
  topic: string;
  updated_at: string;
  workspace_id: string;
}

export interface Profiles {
  created_at: string;
  deleted_at: string | null;
  display_name: string;
  email: string | null;
  handle: string | null;
  id: string | null;
  kind: string;
  metadata_json: Generated<string>;
  revision: Generated<number>;
  status: string;
  updated_at: string;
}

export interface ProjectEnvironmentDefinitions {
  archived_at: string | null;
  created_at: string;
  definition_json: Generated<string>;
  digest: string;
  fingerprint: string;
  id: string | null;
  project_id: string;
  revision: Generated<number>;
  updated_at: string;
  version: number;
  workspace_id: string;
}

export interface ProjectResources {
  access_mode: Generated<string>;
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  is_primary: Generated<number>;
  label: string | null;
  metadata_json: Generated<string>;
  project_id: string;
  resource_key: string;
  revision: Generated<number>;
  status: string;
  updated_at: string;
  workspace_id: string;
}

export interface ProjectResourceSources {
  created_at: string;
  deleted_at: string | null;
  descriptor_json: Generated<string>;
  execution_target_id: string | null;
  id: string | null;
  observed_content_digest: string | null;
  observed_revision: string | null;
  project_id: string;
  resource_id: string;
  revision: Generated<number>;
  source_kind: string;
  updated_at: string;
  workspace_id: string;
}

export interface Projects {
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  description: string | null;
  id: string | null;
  name: string;
  position: number | null;
  revision: Generated<number>;
  settings_json: Generated<string>;
  slug: string;
  status: string;
  updated_at: string;
  workspace_id: string;
}

export interface ProjectStatuses {
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  is_default: Generated<number>;
  is_terminal: Generated<number>;
  key: string;
  metadata_json: Generated<string>;
  name: string;
  position: number;
  project_id: string;
  revision: Generated<number>;
  type: string;
  updated_at: string;
  workspace_id: string;
}

export interface ProjectTags {
  active: Generated<number>;
  color: string | null;
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  label: string;
  project_id: string;
  revision: Generated<number>;
  updated_at: string;
  workspace_id: string;
}

export interface ProjectUserPreferences {
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  preferences_json: Generated<string>;
  project_id: string;
  revision: Generated<number>;
  updated_at: string;
  workspace_id: string;
  workspace_user_id: string;
}

export interface RoleAssignments {
  assigned_by_workspace_user_id: string | null;
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  resource_id: string;
  resource_type: string;
  revision: Generated<number>;
  role_key: string;
  updated_at: string;
  workspace_id: string;
  workspace_user_id: string;
}

export interface RunQueueEntries {
  attempt_count: Generated<number>;
  blocked_reason: string | null;
  created_at: string;
  deleted_at: string | null;
  dispatched_at: string | null;
  enqueued_at: string;
  enqueued_by_workspace_user_id: string | null;
  execution_request_id: string | null;
  id: string | null;
  mission_id: string;
  objective_id: string;
  position: number;
  project_id: string;
  queue_id: string;
  revision: Generated<number>;
  state: string;
  updated_at: string;
  waiting_on_objective_id: string | null;
  waiting_reason: string | null;
  workspace_id: string;
}

export interface RunQueues {
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  id: string | null;
  is_default: Generated<number>;
  mission_id: string | null;
  name: string;
  paused: Generated<number>;
  position: number;
  project_id: string;
  revision: Generated<number>;
  updated_at: string;
  workspace_id: string;
}

export interface Schedules {
  created_at: string;
  days_of_month_json: Generated<string>;
  days_of_week_json: Generated<string>;
  id: string | null;
  name: string | null;
  next_status_key: string | null;
  period_interval: Generated<number>;
  period_type: Generated<string>;
  revision: Generated<number>;
  start_date: string | null;
  timezone: string;
  updated_at: string;
  weeks_of_month_json: Generated<string>;
  workspace_id: string;
}

export interface SchemaMigrations {
  adapter: string;
  applied_at: string;
  checksum: string;
  component: string;
  contract_version: string;
  version: string;
}

export interface SearchDocuments {
  body_text: string;
  content_hash: string | null;
  entity_id: string;
  entity_type: string;
  id: string | null;
  indexed_at: string;
  metadata_json: Generated<string>;
  mission_id: string;
  project_id: string | null;
  source_revision: number | null;
  title: string | null;
  workspace_id: string;
}

export interface SearchDocumentsFts {
  body_text: string | null;
  entity_type: string | null;
  mission_id: string | null;
  title: string | null;
}

export interface SearchDocumentsFtsConfig {
  k: string;
  v: string | null;
}

export interface SearchDocumentsFtsData {
  block: Buffer | null;
  id: Generated<number | null>;
}

export interface SearchDocumentsFtsDocsize {
  id: Generated<number | null>;
  sz: Buffer | null;
}

export interface SearchDocumentsFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface Session {
  createdAt: string;
  expiresAt: string;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface SharedContextEntries {
  created_at: string;
  created_by_session_id: string | null;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  id: string | null;
  key: string;
  mission_id: string;
  objective_id: string | null;
  revision: Generated<number>;
  updated_at: string;
  value_json: string | null;
  value_kind: string;
  value_text: string | null;
  workspace_id: string;
}

export interface StorageBuckets {
  base_url: string | null;
  bucket_key: string;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  id: string | null;
  local_path: string | null;
  organization_id: string | null;
  revision: Generated<number>;
  settings_json: Generated<string>;
  storage_backend: string;
  updated_at: string;
  workspace_id: string | null;
}

export interface TargetResourceObservations {
  branch: string | null;
  created_at: string;
  execution_target_id: string;
  git_commit: string | null;
  git_root: string | null;
  id: string | null;
  observed_at: string;
  resource_id: string;
  state: string;
  updated_at: string;
  workspace_id: string;
}

export interface User {
  createdAt: string;
  email: string;
  emailVerified: Generated<number>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: string;
}

export interface UserExecutionTargetPreferences {
  agent_configs_json: Generated<string>;
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  profile_id: string;
  revision: Generated<number>;
  target_fingerprint: string;
  target_type: string;
  terminal_profile_json: Generated<string>;
  updated_at: string;
}

export interface UserImages {
  alt_text: string | null;
  checksum_sha256: string | null;
  content_type: string;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  filename: string;
  height_px: number | null;
  id: string | null;
  metadata_json: Generated<string>;
  profile_id: string;
  public_url: string | null;
  revision: Generated<number>;
  size_bytes: number | null;
  storage_bucket_id: string;
  storage_key: string;
  updated_at: string;
  width_px: number | null;
  workspace_id: string;
}

export interface UserTokenProjects {
  created_at: string;
  project_id: string;
  token_id: string;
}

export interface UserTokens {
  all_workspaces: Generated<number>;
  created_at: string;
  deleted_at: string | null;
  expires_at: string | null;
  hash_algorithm: string;
  id: string | null;
  label: string;
  last_used_at: string | null;
  last_used_context_json: Generated<string>;
  metadata_json: Generated<string>;
  organization_id: string | null;
  predecessor_token_id: string | null;
  profile_id: string;
  revision: Generated<number>;
  revoked_at: string | null;
  revoked_by_workspace_user_id: string | null;
  scope: Generated<string>;
  status: string;
  token_hash: string;
  token_prefix: string;
  updated_at: string;
  workspace_id: string | null;
  workspace_user_id: string | null;
}

export interface UserTokenScopes {
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  permission: string;
  resource_id: string | null;
  resource_type: string | null;
  revision: Generated<number>;
  token_id: string;
  updated_at: string;
  workspace_id: string;
}

export interface UserTokenWorkspaces {
  created_at: string;
  token_id: string;
  workspace_id: string;
}

export interface Verification {
  createdAt: string | null;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: string | null;
  value: string;
}

export interface WebhookDeliveryAttempts {
  attempt_number: number;
  attempted_at: string;
  duration_ms: number | null;
  error: string | null;
  event_type: string;
  id: string | null;
  outbox_message_id: string;
  response_snippet: string | null;
  response_status: number | null;
  subscription_id: string;
  workspace_id: string;
}

export interface WebhookSubscriptions {
  consecutive_failures: Generated<number>;
  created_at: string;
  created_by_workspace_user_id: string;
  deleted_at: string | null;
  disabled_reason: string | null;
  enabled: Generated<number>;
  endpoint_url: string;
  event_types_json: string;
  id: string | null;
  last_failure_at: string | null;
  last_success_at: string | null;
  name: string;
  payload_mode: Generated<string>;
  project_id: string | null;
  revision: Generated<number>;
  secret: string;
  updated_at: string;
  workspace_id: string;
}

export interface WorkerJobs {
  attempt_count: Generated<number>;
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  last_error: string | null;
  locked_by: string | null;
  locked_until: string | null;
  max_attempts: Generated<number>;
  payload_json: string;
  priority: Generated<number>;
  revision: Generated<number>;
  run_after: string;
  status: Generated<string>;
  type: string;
  updated_at: string;
  workspace_id: string;
}

export interface WorkspaceImages {
  alt_text: string | null;
  checksum_sha256: string | null;
  content_type: string;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  filename: string;
  height_px: number | null;
  id: string | null;
  metadata_json: Generated<string>;
  public_url: string | null;
  revision: Generated<number>;
  size_bytes: number | null;
  storage_bucket_id: string;
  storage_key: string;
  updated_at: string;
  width_px: number | null;
  workspace_id: string;
}

export interface WorkspaceInvitations {
  accepted_at: string | null;
  accepted_by_workspace_user_id: string | null;
  created_at: string;
  deleted_at: string | null;
  email: string;
  expires_at: string;
  hash_algorithm: string;
  id: string | null;
  invited_by_workspace_user_id: string;
  revision: Generated<number>;
  revoked_at: string | null;
  role_key: Generated<string>;
  status: string;
  token_hash: string;
  token_prefix: string;
  updated_at: string;
  workspace_id: string;
}

export interface Workspaces {
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  kind: string;
  name: string;
  organization_id: string;
  revision: Generated<number>;
  settings_json: Generated<string>;
  slug: string;
  updated_at: string;
}

export interface WorkspaceUserExecutionTargets {
  access_status: string;
  created_at: string;
  default_username: string | null;
  deleted_at: string | null;
  execution_target_id: string;
  id: string | null;
  last_connected_at: string | null;
  revision: Generated<number>;
  updated_at: string;
  workspace_id: string;
  workspace_user_id: string;
}

export interface WorkspaceUsers {
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  member_key: string | null;
  metadata_json: Generated<string>;
  profile_id: string;
  revision: Generated<number>;
  status: string;
  updated_at: string;
  workspace_id: string;
}

export interface DB {
  account: Account;
  account_connection_authorizations: AccountConnectionAuthorizations;
  account_connections: AccountConnections;
  agent_requests: AgentRequests;
  agent_session_channels: AgentSessionChannels;
  agent_session_events: AgentSessionEvents;
  agent_session_inputs: AgentSessionInputs;
  agent_sessions: AgentSessions;
  artifacts: Artifacts;
  attachments: Attachments;
  change_rationales: ChangeRationales;
  changed_files: ChangedFiles;
  chat_dependency_set_members: ChatDependencySetMembers;
  chat_dependency_sets: ChatDependencySets;
  chat_diagnostics: ChatDiagnostics;
  chat_event_acks: ChatEventAcks;
  chat_events: ChatEvents;
  chat_evidence: ChatEvidence;
  chat_messages: ChatMessages;
  chat_notifications: ChatNotifications;
  chat_presence: ChatPresence;
  chat_provider_checkpoints: ChatProviderCheckpoints;
  chat_questions: ChatQuestions;
  chat_run_attempts: ChatRunAttempts;
  chat_runs: ChatRuns;
  chat_source_refs: ChatSourceRefs;
  chat_thread_summaries: ChatThreadSummaries;
  chat_threads: ChatThreads;
  chat_tool_calls: ChatToolCalls;
  chat_work_proposal_revisions: ChatWorkProposalRevisions;
  chat_work_proposals: ChatWorkProposals;
  chat_work_receipt_missions: ChatWorkReceiptMissions;
  chat_work_receipts: ChatWorkReceipts;
  deliveries: Deliveries;
  device_push_tokens: DevicePushTokens;
  devices: Devices;
  entity_changes: EntityChanges;
  execution_request_grants: ExecutionRequestGrants;
  execution_request_observations: ExecutionRequestObservations;
  execution_request_snapshots: ExecutionRequestSnapshots;
  execution_requests: ExecutionRequests;
  execution_target_registrations: ExecutionTargetRegistrations;
  execution_target_runner_registrations: ExecutionTargetRunnerRegistrations;
  execution_targets: ExecutionTargets;
  ext_everhour_mission_links: ExtEverhourMissionLinks;
  ext_everhour_project_links: ExtEverhourProjectLinks;
  ext_everhour_user_connections: ExtEverhourUserConnections;
  ext_everhour_workspace_connections: ExtEverhourWorkspaceConnections;
  ext_github_installations: ExtGithubInstallations;
  ext_github_mission_pull_requests: ExtGithubMissionPullRequests;
  ext_github_project_initializations: ExtGithubProjectInitializations;
  ext_github_project_links: ExtGithubProjectLinks;
  ext_github_user_connections: ExtGithubUserConnections;
  ext_github_user_oauth_states: ExtGithubUserOauthStates;
  human_action_resolutions: HumanActionResolutions;
  idempotency_keys: IdempotencyKeys;
  inbox_items: InboxItems;
  live_activity_push_tokens: LiveActivityPushTokens;
  live_activity_start_tokens: LiveActivityStartTokens;
  mission_branch_observations: MissionBranchObservations;
  mission_events: MissionEvents;
  mission_sequences: MissionSequences;
  mission_status_seen: MissionStatusSeen;
  mission_tags: MissionTags;
  mission_target_resources: MissionTargetResources;
  missions: Missions;
  my_mission_positions: MyMissionPositions;
  notification_preferences: NotificationPreferences;
  notifications: Notifications;
  objective_attachments: ObjectiveAttachments;
  objectives: Objectives;
  organizations: Organizations;
  outbox_messages: OutboxMessages;
  profiles: Profiles;
  project_environment_definitions: ProjectEnvironmentDefinitions;
  project_resource_sources: ProjectResourceSources;
  project_resources: ProjectResources;
  project_statuses: ProjectStatuses;
  project_tags: ProjectTags;
  project_user_preferences: ProjectUserPreferences;
  projects: Projects;
  role_assignments: RoleAssignments;
  run_queue_entries: RunQueueEntries;
  run_queues: RunQueues;
  schedules: Schedules;
  schema_migrations: SchemaMigrations;
  search_documents: SearchDocuments;
  search_documents_fts: SearchDocumentsFts;
  search_documents_fts_config: SearchDocumentsFtsConfig;
  search_documents_fts_data: SearchDocumentsFtsData;
  search_documents_fts_docsize: SearchDocumentsFtsDocsize;
  search_documents_fts_idx: SearchDocumentsFtsIdx;
  session: Session;
  shared_context_entries: SharedContextEntries;
  storage_buckets: StorageBuckets;
  target_resource_observations: TargetResourceObservations;
  user: User;
  user_execution_target_preferences: UserExecutionTargetPreferences;
  user_images: UserImages;
  user_token_projects: UserTokenProjects;
  user_token_scopes: UserTokenScopes;
  user_token_workspaces: UserTokenWorkspaces;
  user_tokens: UserTokens;
  verification: Verification;
  webhook_delivery_attempts: WebhookDeliveryAttempts;
  webhook_subscriptions: WebhookSubscriptions;
  worker_jobs: WorkerJobs;
  workspace_images: WorkspaceImages;
  workspace_invitations: WorkspaceInvitations;
  workspace_user_execution_targets: WorkspaceUserExecutionTargets;
  workspace_users: WorkspaceUsers;
  workspaces: Workspaces;
}
